// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  The recorder's state comes along so the meeting being recorded right now is
	 *  never labelled interrupted — mid-recording its files look exactly like a
	 *  killed one's (TUR-97).
	 */
	listMeetings: () => typedError<meet_ai_lib_meetings_list_MeetingList, meet_ai_lib_error_UiError>(__TAURI_INVOKE("list_meetings")),
	readMeeting: (id: string) => typedError<meet_ai_lib_meetings_view_MeetingDetail, meet_ai_lib_error_UiError>(__TAURI_INVOKE("read_meeting", { id })),
	/**
	 *  Through the [`FolderGate`]: a note saved under the old root while the
	 *  folder is moving would be deleted with it.
	 */
	saveNotes: (id: string, body: string) => typedError<null, meet_ai_lib_error_UiError>(__TAURI_INVOKE("save_notes", { id, body })),
	/**
	 *  Move the meetings folder somewhere else, taking every existing meeting
	 *  with it.
	 * 
	 *  Refused while a recording is in flight: the recorder is mid-write to a
	 *  folder under the *old* root, and a move underneath it would either corrupt
	 *  that write or silently vanish the in-progress meeting.
	 * 
	 *  Checking the phase once is not enough now that the move runs off the main
	 *  thread — the window stays live, and Record pressed a second into a
	 *  minutes-long copy would start a meeting under the old root just before
	 *  `move_contents` deletes it. The same goes for notes, the onboarding flag
	 *  and a model download. The [`FolderGate`] move guard is held for the whole
	 *  move, so every one of those writers is refused until it drops (see
	 *  [`folder_move`]). The phase check comes after the guard is taken: from then
	 *  on nothing can leave `Idle`, so the answer cannot go stale mid-move.
	 */
	changeMeetingsFolder: (newRoot: string) => typedError<meet_ai_lib_meetings_list_MeetingList, meet_ai_lib_error_UiError>(__TAURI_INVOKE("change_meetings_folder", { newRoot })),
	/**
	 *  Open a meeting's folder in Finder.
	 * 
	 *  L7 makes the files the product, so "where is it on disk" is a first-class
	 *  question rather than a debugging affordance. Finding the folder reads the
	 *  meeting from disk, so it goes to the blocking pool with the rest.
	 */
	revealMeeting: (id: string) => typedError<null, meet_ai_lib_error_UiError>(__TAURI_INVOKE("reveal_meeting", { id })),
	/**
	 *  Runs the real positive-control check (SPEC §8.1/A6): plays the permission
	 *  chime and probes the microphone. Real wall-clock time, so it runs on a
	 *  blocking thread rather than parking a tokio worker.
	 * 
	 *  If the measurement itself dies (a panic on the blocking thread), the answer
	 *  falls back to the silent check rather than failing the screen — but it is
	 *  logged, because otherwise a broken measurement looks exactly like a working
	 *  one.
	 */
	measurePermission: () => __TAURI_INVOKE<meet_ai_lib_permission_Status>("measure_permission"),
	/**  The silent launch-time check — no chime (see `permission::quick`). */
	permissionQuick: () => __TAURI_INVOKE<meet_ai_lib_permission_Status>("permission_quick"),
	/**
	 *  Open System Settings at the pane the user needs.
	 * 
	 *  Falls back to the Privacy & Security root if the anchored URL is refused,
	 *  which is the behaviour SPEC §8.1 asks for. The on-screen steps name the pane
	 *  as well, so the instructions still work even if both fail.
	 */
	openPrivacySettings: (pane: meet_ai_lib_permission_Pane) => typedError<null, meet_ai_lib_error_UiError>(__TAURI_INVOKE("open_privacy_settings", { pane })),
	/**
	 *  The onboarding flag is a file under the meetings root (see
	 *  [`onboarding`]), so all three go to the blocking pool with the meetings
	 *  commands. `onboarding_state` is on the launch path; a slow or sleeping disk
	 *  must not hold the first paint.
	 */
	onboardingState: () => typedError<meet_ai_lib_onboarding_State, meet_ai_lib_error_UiError>(__TAURI_INVOKE("onboarding_state")),
	/**
	 *  Writes `.app/onboarding.json` under the root, so through the
	 *  [`FolderGate`] like every other writer there.
	 */
	completeOnboarding: () => typedError<meet_ai_lib_onboarding_State, meet_ai_lib_error_UiError>(__TAURI_INVOKE("complete_onboarding")),
	resetOnboarding: () => typedError<meet_ai_lib_onboarding_State, meet_ai_lib_error_UiError>(__TAURI_INVOKE("reset_onboarding")),
	/**
	 *  Filesystem-only, sub-millisecond. The settings route blocks on this.
	 * 
	 *  `config::transcription` is itself a filesystem read, not a probe, so it
	 *  belongs on this side of the cheap/expensive split described in the module
	 *  doc comment. Cheap is still disk, though — the config file, the root
	 *  pointer, a stat per model — so it runs on the blocking pool like every other
	 *  command that touches the filesystem, not on the main thread.
	 */
	engineEnvironment: () => typedError<meet_ai_lib_engine_EnvironmentView, meet_ai_lib_error_UiError>(__TAURI_INVOKE("engine_environment")),
	/**
	 *  Runs `meet-stt --probe`, median ~160 ms. The settings route renders a
	 *  "Checking…" row and calls this after paint.
	 */
	engineSelection: () => typedError<meet_ai_lib_engine_SelectionView, meet_ai_lib_error_UiError>(__TAURI_INVOKE("engine_selection")),
	/**
	 *  A stat per model under the meetings root, which means reading the root
	 *  pointer first — disk, so the blocking pool.
	 */
	modelCatalogue: () => typedError<meet_ai_lib_engine_ModelView[], meet_ai_lib_error_UiError>(__TAURI_INVOKE("model_catalogue")),
	/**
	 *  Download a model, emitting `model://progress` as it goes.
	 * 
	 *  One in-flight download per model: two would resume the same `.part` file
	 *  from two directions and race the atomic rename. The claim that enforces it
	 *  is taken inside `engine::download`, on the thread that writes the file, so
	 *  it lasts exactly as long as the writer does (see `engine::Claim`).
	 */
	downloadModel: (id: string) => typedError<string, meet_ai_lib_error_UiError>(__TAURI_INVOKE("download_model", { id })),
	recordingStatus: () => __TAURI_INVOKE<meet_ai_lib_recording_Status>("recording_status"),
	/**
	 *  Starting or stopping blocks on real wall-clock time — SPEC §8.1's
	 *  positive-control permission measurement on start, Core Audio warming up or
	 *  winding down either side — so both run on a blocking thread rather than
	 *  parking a tokio worker, the same reason `measure_permission` does.
	 * 
	 *  The toggle goes through the [`FolderGate`], the same as ⌘⇧R and the menu
	 *  bar, so the button cannot start a recording while the folder is moving.
	 */
	toggleRecording: () => typedError<meet_ai_lib_recording_Status, meet_ai_lib_error_UiError>(__TAURI_INVOKE("toggle_recording")),
	/**
	 *  Stopping is never gated: a move only runs while nothing is recording, so
	 *  there is nothing for a stop to race.
	 */
	stopRecording: () => typedError<meet_ai_lib_recording_Status, meet_ai_lib_error_UiError>(__TAURI_INVOKE("stop_recording")),
	/**
	 *  Everything the live pane should show right now, so a window opened
	 *  mid-meeting (or reloaded) catches up without replaying events it missed.
	 *  In-memory only and cheap; after this, `transcript://update` and
	 *  `transcript://status` keep it current, deduplicated by `seq`.
	 */
	liveTranscript: () => __TAURI_INVOKE<meet_ai_lib_live_transcript_Snapshot>("live_transcript"),
	/**  Every ticket in the meetings folder, newest first (TUR-102). */
	listTickets: () => typedError<meet_ai_lib_tickets_TicketSummary[], meet_ai_lib_error_UiError>(__TAURI_INVOKE("list_tickets")),
	/**  Add a ticket by hand. Through the [`FolderGate`], like [`save_notes`]. */
	createTicket: (title: string, body: string) => typedError<meet_ai_lib_tickets_TicketSummary, meet_ai_lib_error_UiError>(__TAURI_INVOKE("create_ticket", { title, body })),
	/**
	 *  The Start Work prompt for a ticket, for the window to copy (SPEC L14).
	 *  `meeting_id` is the meeting the ticket is listed under, if any.
	 */
	startWorkPrompt: (ticketId: string, meetingId: string | null) => typedError<string, meet_ai_lib_error_UiError>(__TAURI_INVOKE("start_work_prompt", { ticketId, meetingId })),
	/**
	 *  The clipboard wrap-up prompt for a meeting, for when no agent is set up
	 *  (SPEC A11).
	 */
	wrapUpPrompt: (meetingId: string) => typedError<string, meet_ai_lib_error_UiError>(__TAURI_INVOKE("wrap_up_prompt", { meetingId })),
	/**  Whether the meeting view offers Copy prompt: `agent.harness` is `none`. */
	copyPromptFallback: () => typedError<boolean, meet_ai_lib_error_UiError>(__TAURI_INVOKE("copy_prompt_fallback")),
	/**
	 *  The agent pick in `config.jsonc`. An `agent.harness` the app does not know
	 *  is an `unknown-harness` error, so the screen can point at the picker.
	 */
	agentChoice: () => typedError<meet_ai_lib_agent_setup_AgentChoice, meet_ai_lib_error_UiError>(__TAURI_INVOKE("agent_choice")),
	/**
	 *  Claude Code, then Codex: found or not, signed in or not. Each check can
	 *  take seconds (a login shell, `--version`, the sign-in check), so the two
	 *  run side by side.
	 */
	detectAgents: (choice: meet_ai_lib_agent_setup_AgentChoice) => typedError<meet_ai_lib_agent_setup_AgentCli[], meet_ai_lib_error_UiError>(__TAURI_INVOKE("detect_agents", { choice })),
	/**
	 *  Save the pick into `config.jsonc` and return it as saved. Writes under the
	 *  meetings root, so through the [`FolderGate`] like every other writer.
	 */
	saveAgentChoice: (choice: meet_ai_lib_agent_setup_AgentChoice) => typedError<meet_ai_lib_agent_setup_AgentChoice, meet_ai_lib_error_UiError>(__TAURI_INVOKE("save_agent_choice", { choice })),
	/**
	 *  Run the sample meeting through the picked CLI, the same way the notes run
	 *  after a call does, and return what came back.
	 */
	testAgent: (choice: meet_ai_lib_agent_setup_AgentChoice) => typedError<meet_ai_lib_agent_setup_AgentTestResult, meet_ai_lib_error_UiError>(__TAURI_INVOKE("test_agent", { choice })),
	/**
	 *  Search every meeting's transcript, notes, summary and tickets.
	 * 
	 *  Runs on the blocking pool: the first call after launch can still be
	 *  rebuilding the index, and SQLite is disk work.
	 */
	search: (query: string) => typedError<store_index_Hit[], meet_ai_lib_error_UiError>(__TAURI_INVOKE("search", { query })),
	/**  Where this meeting's notes run stands. */
	notesRunStatus: (meetingId: string) => typedError<meet_ai_lib_agent_run_Status, meet_ai_lib_error_UiError>(__TAURI_INVOKE("notes_run_status", { meetingId })),
	/**
	 *  Start the notes run by hand: Retry, or the first run on a meeting that
	 *  has none. Ignored while one is running; the answer is then that run.
	 */
	startNotesRun: (meetingId: string) => typedError<meet_ai_lib_agent_run_Status, meet_ai_lib_error_UiError>(__TAURI_INVOKE("start_notes_run", { meetingId })),
	/**  Cancel this meeting's running notes run. A no-op when none is running. */
	cancelNotesRun: (meetingId: string) => typedError<meet_ai_lib_agent_run_Status, meet_ai_lib_error_UiError>(__TAURI_INVOKE("cancel_notes_run", { meetingId })),
	/**  The agent-written sections of this meeting's `meeting.md`. */
	meetingNotes: (meetingId: string) => typedError<meet_ai_lib_agent_run_MeetingNotes, meet_ai_lib_error_UiError>(__TAURI_INVOKE("meeting_notes", { meetingId })),
	/**
	 *  Sync one task: one agent run that creates the issue, then the issue's key
	 *  and address written to the ticket. Takes as long as the agent does (up to
	 *  `agent.timeout_sec`), so it runs on the blocking pool.
	 */
	syncTask: (ticketId: string, meetingId: string | null) => typedError<meet_ai_lib_tickets_TicketSummary, meet_ai_lib_error_UiError>(__TAURI_INVOKE("sync_task", { ticketId, meetingId })),
	/**  Stop a running Sync; its `sync_task` then fails with `agent-cancelled`. */
	cancelSync: (ticketId: string) => __TAURI_INVOKE<void>("cancel_sync", { ticketId }),
	/**
	 *  A meeting's tasks: the ones in its own `tickets/` folder, where the notes
	 *  run writes them, and shared ones that name it. Sorted by id.
	 */
	meetingTasks: (meetingId: string) => typedError<meet_ai_lib_tickets_TicketSummary[], meet_ai_lib_error_UiError>(__TAURI_INVOKE("meeting_tasks", { meetingId })),
	/**
	 *  Open a synced task's issue in the browser. The address comes from the
	 *  ticket file and must be `https://`; the webview never opens a URL itself.
	 */
	openSyncedIssue: (ticketId: string, meetingId: string | null) => typedError<null, meet_ai_lib_error_UiError>(__TAURI_INVOKE("open_synced_issue", { ticketId, meetingId })),
	/**  The current tracker settings. */
	trackerSettings: () => typedError<meet_ai_lib_sync_tracker_TrackerSettings, meet_ai_lib_error_UiError>(__TAURI_INVOKE("tracker_settings")),
	/**
	 *  Save the tracker and its MCP server. Through the [`FolderGate`]: the
	 *  config file lives in the meetings folder.
	 */
	setTracker: (tracker: string, trackerMcp: string) => typedError<meet_ai_lib_sync_tracker_TrackerSettings, meet_ai_lib_error_UiError>(__TAURI_INVOKE("set_tracker", { tracker, trackerMcp })),
	/**
	 *  The MCP servers the chosen agent's CLI can see. Claude Code checks each
	 *  server's health, so this can take most of a minute. Empty when no agent
	 *  is chosen.
	 */
	trackerServers: () => typedError<meet_ai_lib_sync_tracker_TrackerServer[], meet_ai_lib_error_UiError>(__TAURI_INVOKE("tracker_servers")),
	/**
	 *  Switch "Make notes for this meeting" on or off (SPEC A11, "Skip one
	 *  meeting", TUR-12), and answer with the meeting's notes as they now stand.
	 * 
	 *  Off writes `agent_notes: off` into `meeting.md` and cancels this
	 *  meeting's notes run if one is going, so nothing more is sent or written.
	 *  On removes the key; the view then offers *Make notes now*, which is
	 *  [`start_notes_run`].
	 */
	setMeetingNotes: (meetingId: string, on: boolean) => typedError<meet_ai_lib_agent_run_MeetingNotes, meet_ai_lib_error_UiError>(__TAURI_INVOKE("set_meeting_notes", { meetingId, on })),
};

/* Constants */
export const AGENT_RUN_STATUS_EVENT = "agent-run://status" as const;

export const MEETINGS_CHANGED_EVENT = "meetings-changed" as const;

export const MODEL_PROGRESS_EVENT = "model://progress" as const;

export const PERMISSION_STATUS_EVENT = "permission://status" as const;

export const RECORDING_STATE_EVENT = "recording://state" as const;

export const TRANSCRIPT_STATUS_EVENT = "transcript://status" as const;

export const TRANSCRIPT_UPDATE_EVENT = "transcript://update" as const;

/* Types */
/**
 *  The pick the Setup screen shows and saves: `agent.harness`, `agent.model`
 *  and `agent.binary_path`.
 */
export type meet_ai_lib_agent_setup_AgentChoice = {
	harness: meet_ai_lib_agent_setup_AgentHarness,
	/**
	 *  Any model name the CLI accepts. Blank for Codex means "Codex's own
	 *  default".
	 */
	model: string,
	/**
	 *  Where the CLI is, when the app cannot find it by itself. `null` (or
	 *  blank) means "look for it".
	 */
	binaryPath: string | null,
};

/**  One agent CLI as the Setup screen lists it. */
export type meet_ai_lib_agent_setup_AgentCli = {
	id: meet_ai_lib_agent_setup_AgentCliId,
	/**  "Claude Code" or "Codex". */
	name: string,
	/**
	 *  The company the transcript goes to, for the privacy sentence:
	 *  "Anthropic" or "OpenAI".
	 */
	provider: string,
	state: meet_ai_lib_agent_setup_AgentCliState,
	/**  Where it was found. `null` when it was not. */
	path: string | null,
	/**  What `--version` printed, if anything usable. */
	version: string | null,
	/**  What to type in Terminal to sign in. */
	signInCommand: string,
	/**  Model names for the picker. The user can still type any other. */
	models: string[],
	/**
	 *  The model picked when the user picks none. `null` for Codex, which
	 *  then uses its own default.
	 */
	defaultModel: string | null,
	/**  Whether the Test button can run. False only when the CLI is missing. */
	canTest: boolean,
};

/**  One of the agent CLIs the app knows how to run. */
export type meet_ai_lib_agent_setup_AgentCliId = "claude-code" | "codex";

/**  Whether a CLI can run right now. */
export type meet_ai_lib_agent_setup_AgentCliState = 
/**  Found, and signed in. */
"ready" | 
/**  Found, but nobody is signed in. */
"signed-out" | 
/**  Not found on this Mac. */
"missing";

/**  `agent.harness`: which CLI runs the notes, or none (copy prompt instead). */
export type meet_ai_lib_agent_setup_AgentHarness = "claude-code" | "codex" | "none";

/**  What the test run wrote from the sample meeting. */
export type meet_ai_lib_agent_setup_AgentTestResult = {
	summary: string,
	decisions: string[],
	openQuestions: string[],
	tasks: meet_ai_lib_agent_setup_AgentTestTask[],
	/**
	 *  How long the run took, in whole seconds (rounded). A whole number so
	 *  the wire type is a plain `number`; an `f64` would be `number | null`.
	 */
	seconds: number,
};

/**  One task from the test run. */
export type meet_ai_lib_agent_setup_AgentTestTask = {
	title: string,
	owner: string | null,
	due: string | null,
};

/**  What the filesystem says, with no subprocess involved. */
export type meet_ai_lib_engine_EnvironmentView = {
	/**
	 *  Absolute path to the `meet-stt` sidecar, if it was found. `None` means
	 *  Apple's engine is not reachable at all on this install.
	 */
	sidecar: string | null,
	/**  Absolute path to a downloaded whisper model, if one is present. */
	whisperModel: string | null,
	locale: string,
	modelId: string,
	/**
	 *  `<meetings root>/.app/models/`, so the screen can name where downloads
	 *  land.
	 */
	modelsDir: string | null,
};

/**  Why a run wrote no notes, in plain words. */
export type meet_ai_lib_agent_run_Failure = {
	kind: meet_ai_lib_agent_run_FailureKind,
	/**  One or two sentences for the meeting view, next to Retry. */
	message: string,
	/**
	 *  A command to type in Terminal that fixes it, when there is one
	 *  (signing in).
	 */
	command: string | null,
};

/**
 *  Every way a run can end without notes. One per thing the user can do
 *  about it.
 */
export type meet_ai_lib_agent_run_FailureKind = 
/**  No agent is set up (`agent.harness` is `none`); Copy prompt instead. */
"no-agent" | 
/**  The chosen agent CLI is not on this Mac, or meet-ai cannot find it. */
"not-installed" | 
/**  The CLI is there but nobody is signed in to it. */
"not-signed-in" | 
/**  The run went past `agent.timeout_sec` and was stopped. */
"timed-out" | 
/**  The user pressed Cancel. */
"cancelled" | 
/**  The CLI exited with an error. */
"cli-failed" | 
/**  The CLI's answer was not JSON, or not in the notes format. */
"bad-reply" | 
/**
 *  The run could not be started (temp folder, launch, prompt template,
 *  config).
 */
"could-not-start" | 
/**  The meeting has no transcript to write notes from. */
"no-transcript" | 
/**  The user switched notes off for this meeting (`agent_notes: off`). */
"notes-off" | 
/**  The answer was fine but writing `meeting.md` or the tickets failed. */
"write-failed";

/**  One search result. */
export type store_index_Hit = {
	meetingId: string,
	title: string,
	date: string | null,
	/**
	 *  The matching text, each matched word wrapped in [`MATCH_START`] and
	 *  [`MATCH_END`].
	 */
	snippet: string,
	/**  `HH:MM:SS` into the recording; `None` for a title, notes or ticket hit. */
	timestamp: string | null,
};

/**
 *  One line on its way to the live pane.
 * 
 *  `start_sec` is fractional here, unlike [`Utterance::start_sec`]. The pane can
 *  show sub-second placement while the `[HH:MM:SS]` line format cannot, and
 *  truncating early would throw the precision away before anyone could use it.
 */
export type stt_session_LiveLine = {
	/**  Meeting-global, monotonic. Stable React key. */
	seq: number,
	speaker: meeting_format_Speaker,
	/**  Seconds from the start of the recording. */
	start_sec: number,
	/**  Already whitespace-collapsed and known non-empty. */
	text: string,
};

/**  A finished meeting, opened for review. */
export type meet_ai_lib_meetings_view_MeetingDetail = {
	summary: meet_ai_lib_meetings_view_MeetingSummary,
	/**  Absolute path, so "Reveal in Finder" and the error copy can name it. */
	path: string,
	lines: meet_ai_lib_meetings_view_TranscriptLine[],
	/**  `transcript.md` is missing entirely — a different state from "empty". */
	transcriptMissing: boolean,
	/**  Lines that did not match §3.4 and were skipped. Surfaced, not hidden. */
	unparsedLineCount: number,
	notes: string,
};

/**  The meeting list plus enough context to write honest empty-state copy. */
export type meet_ai_lib_meetings_list_MeetingList = {
	root: string,
	/**
	 *  The folder does not exist yet. Before the first recording it never does,
	 *  and that is not an error worth alarming anyone about.
	 */
	rootExists: boolean,
	meetings: meet_ai_lib_meetings_view_MeetingSummary[],
};

/**  The agent-written half of `meeting.md`, for the meeting view. */
export type meet_ai_lib_agent_run_MeetingNotes = {
	/**  The meeting is marked `agent_notes: off`. */
	notesOff: boolean,
	/**
	 *  `analyzed_by` (`claude-code`, `codex`, `clipboard`), `None` before any
	 *  notes were written.
	 */
	analyzedBy: string | null,
	/**
	 *  The four sections (Summary, Decisions, Action Items, Open Questions)
	 *  that have text, in that order. Bodies are markdown as written.
	 */
	sections: meet_ai_lib_agent_run_NotesSection[],
};

/**  One row in the meeting list. */
export type meet_ai_lib_meetings_view_MeetingSummary = {
	/**  The folder name, e.g. `2026-09-01-1430-standup`. Also the route param. */
	id: string,
	/**  What to show in the list. */
	title: string,
	/**  `YYYY-MM-DD`, parsed from the folder name. `None` if it does not match. */
	date: string | null,
	/**  `HH:MM`, parsed from the folder name. */
	time: string | null,
	/**  How many §3.4 lines parsed. 0 is a real, displayable answer. */
	lineCount: number,
	/**  The timestamp on the last parsed line — the meeting's readable length. */
	lastTimestamp: string | null,
	/**  `notes.md` exists and has something in it. */
	hasNotes: boolean,
	/**
	 *  The meeting has been wrapped up: `meeting.md` exists and its notes are
	 *  written (`analyzed_by` is set, or one of the four sections has text).
	 *  A `meeting.md` that holds only the notes switch does not count.
	 */
	hasAnalysis: boolean,
	/**
	 *  `meeting.md` says `agent_notes: off`: the user switched notes off for
	 *  this meeting (SPEC A11, TUR-12), so no notes run sends it.
	 */
	notesOff: boolean,
	/**  Whether the recording ended on purpose. See [`RecordingState`]. */
	recordingState: meet_ai_lib_recording_state_RecordingState,
	/**
	 *  Milliseconds of audio a player can actually reach: the longer of the
	 *  two tracks, measured from its WAV header (SPEC A5 — header frames are
	 *  the only true duration). `None` when the folder holds no audio at all,
	 *  which is also what a meeting looks like after the retention job (L16)
	 *  has deleted its WAVs.
	 */
	audioMs: number | null,
};

/**  One row on the model download screen. */
export type meet_ai_lib_engine_ModelView = {
	id: string,
	filename: string,
	/**
	 *  The pinned size. SPEC §2.4's "~1.6 GB" is stale — amendment A4 corrects
	 *  it to 574 MB for turbo and 190 MB for small.en — so the screen reads
	 *  `spec.bytes` rather than quoting either document.
	 */
	bytes: number,
	installed: boolean,
};

export type meet_ai_lib_agent_run_NotesSection = {
	heading: string,
	body: string,
};

/**
 *  System Settings panes worth deep-linking to.
 * 
 *  SPEC §8.1 left the exact audio-capture anchor to be "verified at
 *  implementation time, falling back to the pane root". Verified on macOS 27.0
 *  (build 26A428) by reading the anchor table out of the Settings extension:
 * 
 *  ```text
 *  strings /System/Library/ExtensionKit/Extensions/SecurityPrivacyExtension.appex/\
 *    Contents/MacOS/SecurityPrivacyExtension | grep -oE 'Privacy_[A-Za-z0-9]+'
 *  ```
 * 
 *  `Privacy_AudioCapture` and `Privacy_Microphone` are both in that table. The
 *  pane root stays here as the third entry because an unknown anchor lands on
 *  the root anyway, and because this list will be wrong on some future macOS.
 */
export type meet_ai_lib_permission_Pane = 
/**  "System Audio Recording Only" — the tap permission. */
"audio-capture" | 
/**  The microphone half, which is a separate grant. */
"microphone";

/**
 *  Where the recorder is right now.
 * 
 *  `Starting` and `Stopping` are not decoration: opening the tap (and, on
 *  start, the SPEC §8.1 permission measurement ahead of it) and flushing the
 *  last WAV header both take long enough to see, and a shortcut pressed twice
 *  in that window must be ignored rather than queued.
 */
export type meet_ai_lib_recording_phase_Phase = "idle" | "starting" | "recording" | "stopping";

/**
 *  How a meeting's recording ended, as the UI names it (TUR-97).
 * 
 *  **The name for a partly written meeting is "Interrupted".** Chosen over the
 *  alternatives because it says what happened and nothing more:
 * 
 *  * not *failed*, *corrupt* or *error* — the audio and transcript up to the
 *    cut are good, and opening the meeting is not a failure;
 *  * not *incomplete* or *partial* — those suggest the rest might still turn
 *    up, or that the user should go and find it;
 *  * not *recovered* — that implies a repair step the user took part in, and
 *    TUR-97 says there is none;
 *  * and not *finished*, because it is not one: the recording ended because
 *    the app or the Mac stopped, not because someone pressed Stop.
 * 
 *  The list shows the word as a label; the meeting itself says in one line
 *  how much audio was kept.
 */
export type meet_ai_lib_recording_state_RecordingState = 
/**
 *  Stopped on purpose, or there is no audio to judge by (a folder from
 *  before recording existed, or one whose WAVs retention has deleted).
 */
"finished" | 
/**
 *  The recording was cut short — force quit, `kill -9`, a crash, the
 *  battery. Opened exactly like any other meeting.
 */
"interrupted" | 
/**
 *  This app is writing to it right now. Its files look the way an
 *  interrupted meeting's do — the headers are behind the samples and the
 *  last segment has not been closed — because it has not been stopped
 *  *yet*, so it must never be labelled interrupted.
 */
"recording";

/**  Which engine this Mac will actually use, and why. */
export type meet_ai_lib_engine_SelectionView = {
	/**  `apple-speech` or `whisper`. The canonical names from `stt::registry`. */
	engine: string,
	/**  A whole sentence, written by the registry. Shown as-is. */
	reason: string,
};

/**
 *  What the CLI says about a server. Claude Code checks each one; Codex only
 *  reports it as set up.
 */
export type meet_ai_lib_sync_tracker_ServerStatus = "connected" | "needs_auth" | "failed" | "pending" | "disabled" | "configured" | "unknown";

/**
 *  What the `live_transcript` command returns: enough for a window opened
 *  mid-meeting to draw exactly what an always-open one shows.
 */
export type meet_ai_lib_live_transcript_Snapshot = {
	status: meet_ai_lib_live_transcript_Status,
	/**  Every settled line of the current meeting, in arrival order. */
	finals: stt_session_LiveLine[],
	/**  At most one live hypothesis per speaker. */
	volatile: stt_session_LiveLine[],
};

/**
 *  The two speaker labels v1 can produce (L5).
 * 
 *  Serializes lowercase (`"you"`/`"others"`), which is what the live
 *  transcript events carry. That is a wire name, not the file's: the label
 *  written into `transcript.md` is [`Speaker::label`], capitalised, and a
 *  reader that hands parsed lines to the UI serializes that instead (see
 *  `store::transcript::Line`).
 */
export type meeting_format_Speaker = 
/**  The microphone channel — the person using this Mac. */
"you" | 
/**  The system-audio channel — everyone else on the call. */
"others";

/**
 *  The run's state. `idle` means no run for this meeting since launch: the
 *  view then goes by what is on disk (notes there or not).
 */
export type meet_ai_lib_agent_run_State = { state: "idle" } | 
/**  *Writing notes…*, with Cancel. */
{ state: "running" } | 
/**
 *  The notes and tasks are on disk. `tasks` is how many tickets were
 *  written.
 */
{ state: "done"; tasks: number } | 
/**  No notes were written, and why. Retry starts again. */
{ state: "failed"; failure: meet_ai_lib_agent_run_Failure };

/**  Where live transcription is. */
export type meet_ai_lib_live_transcript_State = 
/**  Not transcribing: no meeting yet, or the engine is still loading. */
"idle" | 
/**  Lines are being produced. */
"running" | 
/**  The meeting ended and every line that settled is in `transcript.md`. */
"stopped" | 
/**  Transcription ended early. `detail` says why; the recording did not. */
"failed";

/**
 *  Whether onboarding is done, and when.
 * 
 *  One nullable timestamp rather than a boolean plus a date: two fields can
 *  disagree, and "completed but with no date" is a state nobody wants to have
 *  to reason about. The frontend reads `completedAt !== null`.
 */
export type meet_ai_lib_onboarding_State = {
	/**
	 *  When the user finished onboarding, as an RFC 3339 string. `None` means
	 *  they have not.
	 */
	completedAt: string | null,
};

/**  Where the user stands with audio permission. */
export type meet_ai_lib_permission_State = 
/**
 *  Not measured yet. The honest answer until the positive-control tone
 *  check exists.
 */
"unknown" | 
/**  The positive control came back. Recording will capture real audio. */
"granted" | 
/**  The user said No, or the tone did not come back. */
"denied";

/**  Where one meeting's notes run stands, as the meeting view shows it. */
export type meet_ai_lib_agent_run_Status = {
	/**  The meeting folder name. */
	meetingId: string,
	state: meet_ai_lib_agent_run_State,
};

/**  What [`TRANSCRIPT_STATUS_EVENT`] carries. */
export type meet_ai_lib_live_transcript_Status = {
	state: meet_ai_lib_live_transcript_State,
	/**  `apple-speech` or `whisper`, once one has been opened. */
	engine: string | null,
	/**  A sentence for the user when `state` is `failed`. */
	detail: string | null,
};

/**  The permission answer plus enough context for the screen to explain itself. */
export type meet_ai_lib_permission_Status = {
	state: meet_ai_lib_permission_State,
	/**
	 *  Whether a real measurement produced this, or it is the placeholder.
	 * 
	 *  The onboarding screen shows different copy for "we checked and you are
	 *  fine" versus "we cannot check yet", and it must not conflate them.
	 */
	measured: boolean,
	/**
	 *  One sentence naming how the answer was reached. Shown in small print
	 *  under the status row, never in place of the status itself.
	 */
	detail: string,
	/**
	 *  Which grants are off, as the System Settings pane each one lives in, so
	 *  the screen can name the switch to flip rather than "audio" in general.
	 *  Empty unless `state` is `Denied`.
	 */
	denied: meet_ai_lib_permission_Pane[],
};

/**  The recorder's state as the webview sees it. */
export type meet_ai_lib_recording_Status = {
	phase: meet_ai_lib_recording_phase_Phase,
	/**  The folder name of the meeting being recorded, `None` when idle. */
	meetingId: string | null,
	/**
	 *  Unix epoch milliseconds the recording started, so the UI can run its own
	 *  timer instead of being fed a tick per second over IPC.
	 */
	startedAtMs: number | null,
	/**
	 *  Why the last recording ended badly, or the last start was refused: it
	 *  stopped on its own because a tick failed (TUR-97), it did not close
	 *  cleanly, or a start from ⌘⇧R, the menu bar or the button was turned
	 *  down (TUR-127). Only ever set on an `Idle` status, and cleared by the
	 *  next start. It rides on the state event because most of these have no
	 *  command call waiting to return an error to — a recording that ends on
	 *  its own, or a shortcut pressed with the window hidden — and one event
	 *  for the move to `Idle` and its reason means the window can never show
	 *  one without the other. Serialised as `null` when nothing went wrong.
	 */
	error: meet_ai_lib_error_UiError | null,
};

/**  One ticket as the webview sees it. */
export type meet_ai_lib_tickets_TicketSummary = {
	id: string,
	title: string,
	/**
	 *  `open`, `in_progress`, `done` or `dropped`; `None` when missing or
	 *  not one of those.
	 */
	status: string | null,
	/**  The meeting folder id it came from; `None` for a hand-made ticket. */
	meeting: string | null,
	body: string,
	/**  The file needs attention (bad YAML, missing id, odd status, ...). */
	hasProblems: boolean,
	/**
	 *  The tracker it was synced to (`linear`, `jira`, `github`); `None`
	 *  until a Sync run created the issue (TUR-11).
	 */
	syncedTo: string | null,
	/**  The issue key the tracker gave it, e.g. `ENG-42`. */
	externalId: string | null,
	/**  The issue's web address. */
	externalUrl: string | null,
};

/**  One MCP server the agent's CLI lists. */
export type meet_ai_lib_sync_tracker_TrackerServer = {
	name: string,
	status: meet_ai_lib_sync_tracker_ServerStatus,
};

/**  The tracker settings as the window sees them. */
export type meet_ai_lib_sync_tracker_TrackerSettings = {
	/**  `linear`, `jira` or `github`. */
	tracker: string,
	/**  The MCP server name as the agent's CLI lists it. */
	trackerMcp: string,
	/**  `agent.harness`: `claude-code`, `codex` or `none`. */
	harness: string,
};

/**  One parsed transcript line. */
export type meet_ai_lib_meetings_view_TranscriptLine = {
	/**  0-based line number within `transcript.md`, per the Phase 2a contract. */
	seq: number,
	/**  `HH:MM:SS`, the utterance *start* (SPEC §3.4). */
	time: string,
	/**  `You` or `Others` (L5). Kept as the literal spec string. */
	speaker: string,
	text: string,
};

/**  An error as the webview sees it. */
export type meet_ai_lib_error_UiError = {
	/**  Which error enum this came from: `stt`, `model`, or `app`. */
	domain: string,
	/**  The stable variant tag. Safe to `switch` on. */
	kind: string,
	/**  The error's own sentence. Display it; do not parse it. */
	message: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

