// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  The recorder's state comes along so the meeting being recorded right now is
	 *  never labelled interrupted — mid-recording its files look exactly like a
	 *  killed one's (TUR-97).
	 */
	listMeetings: () => typedError<meet_ai_lib_meetings_list_MeetingList, meet_ai_lib_error_UiError>(__TAURI_INVOKE("list_meetings")),
	readMeeting: (id: string) => typedError<meet_ai_lib_meetings_view_MeetingDetail, meet_ai_lib_error_UiError>(__TAURI_INVOKE("read_meeting", { id })),
	/**
	 *  Through the [`FolderGate`]: a note saved under the old root while the
	 *  folder is moving would be deleted with it.
	 */
	saveNotes: (id: string, body: string) => typedError<null, meet_ai_lib_error_UiError>(__TAURI_INVOKE("save_notes", { id, body })),
	/**
	 *  Rename a meeting from its page (TUR-103), and answer with the title as
	 *  written: one line, trimmed, at most `store::meeting_title::MAX_TITLE_CHARS`
	 *  characters. A blank title is refused.
	 * 
	 *  Through the [`FolderGate`], like [`save_notes`]. Not noted as our own
	 *  write, so the watcher still tells the window. The search index is updated
	 *  here, as it is after the calendar's and the agent's titles (TUR-107).
	 */
	renameMeeting: (id: string, title: string) => typedError<string, meet_ai_lib_error_UiError>(__TAURI_INVOKE("rename_meeting", { id, title })),
	/**
	 *  Move the meetings folder somewhere else, taking every existing meeting
	 *  with it.
	 * 
	 *  Refused while a recording is in flight: the recorder is mid-write to a
	 *  folder under the *old* root, and a move underneath it would either corrupt
	 *  that write or silently vanish the in-progress meeting.
	 * 
	 *  Checking the phase once is not enough now that the move runs off the main
	 *  thread — the window stays live, and Record pressed a second into a
	 *  minutes-long copy would start a meeting under the old root just before
	 *  `move_contents` deletes it. The same goes for notes, the onboarding flag
	 *  and a model download. The [`FolderGate`] move guard is held for the whole
	 *  move, so every one of those writers is refused until it drops (see
	 *  [`folder_move`]). The phase check comes after the guard is taken: from then
	 *  on nothing can leave `Idle`, so the answer cannot go stale mid-move.
	 */
	changeMeetingsFolder: (newRoot: string) => typedError<meet_ai_lib_meetings_list_MeetingList, meet_ai_lib_error_UiError>(__TAURI_INVOKE("change_meetings_folder", { newRoot })),
	/**
	 *  Open a meeting's folder in Finder.
	 * 
	 *  L7 makes the files the product, so "where is it on disk" is a first-class
	 *  question rather than a debugging affordance. Finding the folder reads the
	 *  meeting from disk, so it goes to the blocking pool with the rest.
	 */
	revealMeeting: (id: string) => typedError<null, meet_ai_lib_error_UiError>(__TAURI_INVOKE("reveal_meeting", { id })),
	/**
	 *  Move one meeting's folder to the Trash.
	 * 
	 *  Through the [`FolderGate`] like every other write under the root, so a
	 *  folder move cannot run at the same time. The recorder's state is read
	 *  inside it: while the gate is held for writing no move can start, and a
	 *  new recording always makes a new folder, never this one. The meeting's
	 *  notes run, if one is going, is cancelled first so its agent stops writing
	 *  into a folder that is about to go. The search index then drops the
	 *  meeting. The folder watcher tells the window the list changed, and the
	 *  window also reloads it itself.
	 */
	deleteMeeting: (id: string) => typedError<null, meet_ai_lib_error_UiError>(__TAURI_INVOKE("delete_meeting", { id })),
	/**
	 *  Runs the real positive-control check (SPEC §8.1/A6): plays the permission
	 *  chime and probes the microphone. Real wall-clock time, so it runs on a
	 *  blocking thread rather than parking a tokio worker.
	 * 
	 *  If the measurement itself dies (a panic on the blocking thread), the answer
	 *  falls back to the silent check rather than failing the screen — but it is
	 *  logged, because otherwise a broken measurement looks exactly like a working
	 *  one.
	 */
	measurePermission: () => __TAURI_INVOKE<meet_ai_lib_permission_Status>("measure_permission"),
	/**  The silent launch-time check — no chime (see `permission::quick`). */
	permissionQuick: () => __TAURI_INVOKE<meet_ai_lib_permission_Status>("permission_quick"),
	/**
	 *  Open the OS settings page the user needs (TUR-51: per OS, see
	 *  [`crate::settings_links`]).
	 * 
	 *  On macOS that is the anchored Privacy & Security pane, falling back to the
	 *  pane root if the anchor is refused, which is the behaviour SPEC §8.1 asks
	 *  for. The on-screen steps name the pane as well, so the instructions still
	 *  work even if both fail.
	 */
	openPrivacySettings: (pane: meet_ai_lib_permission_Pane) => typedError<null, meet_ai_lib_error_UiError>(__TAURI_INVOKE("open_privacy_settings", { pane })),
	/**
	 *  The onboarding flag is a file under the meetings root (see
	 *  [`onboarding`]), so all three go to the blocking pool with the meetings
	 *  commands. `onboarding_state` is on the launch path; a slow or sleeping disk
	 *  must not hold the first paint.
	 */
	onboardingState: () => typedError<meet_ai_lib_onboarding_State, meet_ai_lib_error_UiError>(__TAURI_INVOKE("onboarding_state")),
	/**
	 *  Writes `.app/onboarding.json` under the root, so through the
	 *  [`FolderGate`] like every other writer there.
	 */
	completeOnboarding: () => typedError<meet_ai_lib_onboarding_State, meet_ai_lib_error_UiError>(__TAURI_INVOKE("complete_onboarding")),
	resetOnboarding: () => typedError<meet_ai_lib_onboarding_State, meet_ai_lib_error_UiError>(__TAURI_INVOKE("reset_onboarding")),
	/**
	 *  Filesystem-only, sub-millisecond. The settings route blocks on this.
	 * 
	 *  `config::transcription` is itself a filesystem read, not a probe, so it
	 *  belongs on this side of the cheap/expensive split described in the module
	 *  doc comment. Cheap is still disk, though — the config file, the root
	 *  pointer, a stat per model — so it runs on the blocking pool like every other
	 *  command that touches the filesystem, not on the main thread.
	 */
	engineEnvironment: () => typedError<meet_ai_lib_engine_EnvironmentView, meet_ai_lib_error_UiError>(__TAURI_INVOKE("engine_environment")),
	/**
	 *  Runs `meet-stt --probe`, median ~160 ms. The settings route renders a
	 *  "Checking…" row and calls this after paint.
	 */
	engineSelection: () => typedError<meet_ai_lib_engine_SelectionView, meet_ai_lib_error_UiError>(__TAURI_INVOKE("engine_selection")),
	/**
	 *  A stat per model under the meetings root, which means reading the root
	 *  pointer first — disk, so the blocking pool.
	 */
	modelCatalogue: () => typedError<meet_ai_lib_engine_ModelView[], meet_ai_lib_error_UiError>(__TAURI_INVOKE("model_catalogue")),
	/**
	 *  Download a model, emitting `model://progress` as it goes.
	 * 
	 *  One in-flight download per model: two would resume the same `.part` file
	 *  from two directions and race the atomic rename. The claim that enforces it
	 *  is taken inside `engine::download`, on the thread that writes the file, so
	 *  it lasts exactly as long as the writer does (see `engine::Claim`).
	 */
	downloadModel: (id: string) => typedError<string, meet_ai_lib_error_UiError>(__TAURI_INVOKE("download_model", { id })),
	/**
	 *  Delete a downloaded whisper model that is not picked and not in use
	 *  (TUR-132). Refuses with `model-in-use` otherwise.
	 */
	deleteModel: (id: string) => typedError<null, meet_ai_lib_error_UiError>(__TAURI_INVOKE("delete_model", { id })),
	/**
	 *  The Settings engine picker (TUR-75): the saved choice, what "Automatic"
	 *  lands on, and which choices this Mac can run. Runs the ~160 ms probe.
	 */
	engineChoices: () => typedError<meet_ai_lib_engine_choices_EngineChoices, meet_ai_lib_error_UiError>(__TAURI_INVOKE("engine_choices")),
	/**
	 *  The model licences Settings, About must credit (TUR-62: Parakeet's
	 *  CC-BY-4.0). Constant data, no disk.
	 */
	modelCredits: () => __TAURI_INVOKE<meet_ai_lib_engine_parakeet_ModelCredit[]>("model_credits"),
	/**
	 *  Save `transcription.engine` and `transcription.model` into config.jsonc,
	 *  keeping the rest of the file. Takes effect on the next recording. Writes
	 *  under the meetings root, so through the [`FolderGate`].
	 */
	setTranscription: (engine: meet_ai_lib_engine_choices_EngineChoice, model: string) => typedError<meet_ai_lib_engine_choices_EngineChoices, meet_ai_lib_error_UiError>(__TAURI_INVOKE("set_transcription", { engine, model })),
	/**
	 *  Save `transcription.language` into config.jsonc: `auto`, or the whisper
	 *  code people speak, such as `mr`. Takes effect on the next recording.
	 */
	setSpokenLanguage: (language: string) => typedError<meet_ai_lib_engine_choices_EngineChoices, meet_ai_lib_error_UiError>(__TAURI_INVOKE("set_spoken_language", { language })),
	recordingStatus: () => __TAURI_INVOKE<meet_ai_lib_recording_Status>("recording_status"),
	/**
	 *  Starting or stopping blocks on real wall-clock time — SPEC §8.1's
	 *  positive-control permission measurement on start, Core Audio warming up or
	 *  winding down either side — so both run on a blocking thread rather than
	 *  parking a tokio worker, the same reason `measure_permission` does.
	 * 
	 *  The toggle goes through the [`FolderGate`], the same as ⌘⇧R and the menu
	 *  bar, so the button cannot start a recording while the folder is moving.
	 */
	toggleRecording: () => typedError<meet_ai_lib_recording_Status, meet_ai_lib_error_UiError>(__TAURI_INVOKE("toggle_recording")),
	/**
	 *  Stopping is never gated: a move only runs while nothing is recording, so
	 *  there is nothing for a stop to race.
	 */
	stopRecording: () => typedError<meet_ai_lib_recording_Status, meet_ai_lib_error_UiError>(__TAURI_INVOKE("stop_recording")),
	/**
	 *  Pause the live recording (TUR-146): nothing is written or transcribed
	 *  until [`resume_recording`], and the timer stops. Instant: the ticker
	 *  thread stops the audio at its next tick. Not a recording: no change.
	 */
	pauseRecording: () => __TAURI_INVOKE<meet_ai_lib_recording_Status>("pause_recording"),
	/**  Carry on recording into the same meeting after [`pause_recording`]. */
	resumeRecording: () => __TAURI_INVOKE<meet_ai_lib_recording_Status>("resume_recording"),
	/**
	 *  Everything the live pane should show right now, so a window opened
	 *  mid-meeting (or reloaded) catches up without replaying events it missed.
	 *  In-memory only and cheap; after this, `transcript://update` and
	 *  `transcript://status` keep it current, deduplicated by `seq`.
	 */
	liveTranscript: () => __TAURI_INVOKE<meet_ai_lib_live_transcript_Snapshot>("live_transcript"),
	/**  Every ticket in the meetings folder, newest first (TUR-102). */
	listTickets: () => typedError<meet_ai_lib_tickets_TicketSummary[], meet_ai_lib_error_UiError>(__TAURI_INVOKE("list_tickets")),
	/**  Add a ticket by hand. Through the [`FolderGate`], like [`save_notes`]. */
	createTicket: (title: string, body: string) => typedError<meet_ai_lib_tickets_TicketSummary, meet_ai_lib_error_UiError>(__TAURI_INVOKE("create_ticket", { title, body })),
	/**
	 *  The Start Work prompt for a ticket, for the window to copy (SPEC L14).
	 *  `meeting_id` is the meeting the ticket is listed under, if any.
	 */
	startWorkPrompt: (ticketId: string, meetingId: string | null) => typedError<string, meet_ai_lib_error_UiError>(__TAURI_INVOKE("start_work_prompt", { ticketId, meetingId })),
	/**
	 *  The clipboard wrap-up prompt for a meeting, for when no agent is set up
	 *  (SPEC A11).
	 */
	wrapUpPrompt: (meetingId: string) => typedError<string, meet_ai_lib_error_UiError>(__TAURI_INVOKE("wrap_up_prompt", { meetingId })),
	/**  Whether the meeting view offers Copy prompt: `agent.harness` is `none`. */
	copyPromptFallback: () => typedError<boolean, meet_ai_lib_error_UiError>(__TAURI_INVOKE("copy_prompt_fallback")),
	/**
	 *  The agent pick in `config.jsonc`. An `agent.harness` the app does not know
	 *  is an `unknown-harness` error, so the screen can point at the picker.
	 */
	agentChoice: () => typedError<meet_ai_lib_agent_setup_AgentChoice, meet_ai_lib_error_UiError>(__TAURI_INVOKE("agent_choice")),
	/**
	 *  Claude Code, then Codex: found or not, signed in or not. Each check can
	 *  take seconds (a login shell, `--version`, the sign-in check), so the two
	 *  run side by side.
	 */
	detectAgents: (choice: meet_ai_lib_agent_setup_AgentChoice) => typedError<meet_ai_lib_agent_setup_AgentCli[], meet_ai_lib_error_UiError>(__TAURI_INVOKE("detect_agents", { choice })),
	/**
	 *  Save the pick into `config.jsonc` and return it as saved. Writes under the
	 *  meetings root, so through the [`FolderGate`] like every other writer.
	 */
	saveAgentChoice: (choice: meet_ai_lib_agent_setup_AgentChoice) => typedError<meet_ai_lib_agent_setup_AgentChoice, meet_ai_lib_error_UiError>(__TAURI_INVOKE("save_agent_choice", { choice })),
	/**
	 *  Run the sample meeting through the picked CLI, the same way the notes run
	 *  after a call does, and return what came back. Quitting stops it
	 *  ([`TestRuns::shutdown`], TUR-160).
	 */
	testAgent: (choice: meet_ai_lib_agent_setup_AgentChoice) => typedError<meet_ai_lib_agent_setup_AgentTestResult, meet_ai_lib_error_UiError>(__TAURI_INVOKE("test_agent", { choice })),
	/**
	 *  `agent.auto_run`: true when notes start on their own after a call, false
	 *  when they start only from the meeting's "Make notes now" (TUR-101).
	 */
	notesAutoRun: () => typedError<boolean, meet_ai_lib_error_UiError>(__TAURI_INVOKE("notes_auto_run")),
	/**
	 *  Save `agent.auto_run`, keeping the rest of `agent`, and return it as read
	 *  back from disk. Through the [`FolderGate`] like every other writer.
	 */
	saveNotesAutoRun: (on: boolean) => typedError<boolean, meet_ai_lib_error_UiError>(__TAURI_INVOKE("save_notes_auto_run", { on })),
	/**
	 *  Search every meeting's transcript, notes, summary and tickets.
	 * 
	 *  Runs on the blocking pool: the first call after launch can still be
	 *  rebuilding the index, and SQLite is disk work.
	 */
	search: (query: string) => typedError<store_index_Hit[], meet_ai_lib_error_UiError>(__TAURI_INVOKE("search", { query })),
	/**  Where this meeting's notes run stands. */
	notesRunStatus: (meetingId: string) => typedError<meet_ai_lib_agent_run_Status, meet_ai_lib_error_UiError>(__TAURI_INVOKE("notes_run_status", { meetingId })),
	/**
	 *  Start the notes run by hand: Retry, or the first run on a meeting that
	 *  has none. Ignored while one is running; the answer is then that run.
	 */
	startNotesRun: (meetingId: string) => typedError<meet_ai_lib_agent_run_Status, meet_ai_lib_error_UiError>(__TAURI_INVOKE("start_notes_run", { meetingId })),
	/**  Cancel this meeting's running notes run. A no-op when none is running. */
	cancelNotesRun: (meetingId: string) => typedError<meet_ai_lib_agent_run_Status, meet_ai_lib_error_UiError>(__TAURI_INVOKE("cancel_notes_run", { meetingId })),
	/**  The agent-written sections of this meeting's `meeting.md`. */
	meetingNotes: (meetingId: string) => typedError<meet_ai_lib_agent_run_MeetingNotes, meet_ai_lib_error_UiError>(__TAURI_INVOKE("meeting_notes", { meetingId })),
	/**
	 *  Sync one task: one agent run that creates the issue, then the issue's key
	 *  and address written to the ticket. Takes as long as the agent does (up to
	 *  `agent.timeout_sec`), so it runs on the blocking pool.
	 */
	syncTask: (ticketId: string, meetingId: string | null) => typedError<meet_ai_lib_tickets_TicketSummary, meet_ai_lib_error_UiError>(__TAURI_INVOKE("sync_task", { ticketId, meetingId })),
	/**  Stop a running Sync; its `sync_task` then fails with `agent-cancelled`. */
	cancelSync: (ticketId: string, meetingId: string | null) => __TAURI_INVOKE<void>("cancel_sync", { ticketId, meetingId }),
	/**
	 *  Forget the issue a Sync created but could not attach to this task
	 *  (`sync-not-saved`, `sync-not-attached`), so the next Sync runs afresh. The
	 *  window shows the issue's link until the user dismisses it.
	 */
	dismissUnsavedSync: (ticketId: string, meetingId: string | null) => typedError<null, meet_ai_lib_error_UiError>(__TAURI_INVOKE("dismiss_unsaved_sync", { ticketId, meetingId })),
	/**
	 *  A meeting's tasks: the ones in its own `tickets/` folder, where the notes
	 *  run writes them, and shared ones that name it. Sorted by id.
	 */
	meetingTasks: (meetingId: string) => typedError<meet_ai_lib_tickets_TicketSummary[], meet_ai_lib_error_UiError>(__TAURI_INVOKE("meeting_tasks", { meetingId })),
	/**
	 *  Open a synced task's issue in the browser. The address comes from the
	 *  ticket file and must be `https://`; the webview never opens a URL itself.
	 */
	openSyncedIssue: (ticketId: string, meetingId: string | null) => typedError<null, meet_ai_lib_error_UiError>(__TAURI_INVOKE("open_synced_issue", { ticketId, meetingId })),
	/**
	 *  Approve one of a meeting's suggested tasks: it moves to Tickets, keeping
	 *  its id and meeting. Returns it as Tickets now lists it.
	 */
	approveTask: (meetingId: string, ticketId: string) => typedError<meet_ai_lib_tickets_TicketSummary, meet_ai_lib_error_UiError>(__TAURI_INVOKE("approve_task", { meetingId, ticketId })),
	/**
	 *  Approve every suggested task of a meeting that is still a suggestion.
	 *  Returns the meeting's tasks as they now are, as `meeting_tasks` does. A
	 *  task whose file cannot be moved stays a suggestion.
	 */
	approveAllTasks: (meetingId: string) => typedError<meet_ai_lib_tickets_TicketSummary[], meet_ai_lib_error_UiError>(__TAURI_INVOKE("approve_all_tasks", { meetingId })),
	/**
	 *  Discard one of a meeting's suggested tasks: its file is deleted and its
	 *  number is never handed out again.
	 */
	discardTask: (meetingId: string, ticketId: string) => typedError<null, meet_ai_lib_error_UiError>(__TAURI_INVOKE("discard_task", { meetingId, ticketId })),
	/**  The current tracker settings. */
	trackerSettings: () => typedError<meet_ai_lib_sync_tracker_TrackerSettings, meet_ai_lib_error_UiError>(__TAURI_INVOKE("tracker_settings")),
	/**
	 *  Save the tracker and its MCP server. Through the [`FolderGate`]: the
	 *  config file lives in the meetings folder.
	 */
	setTracker: (tracker: string, trackerMcp: string) => typedError<meet_ai_lib_sync_tracker_TrackerSettings, meet_ai_lib_error_UiError>(__TAURI_INVOKE("set_tracker", { tracker, trackerMcp })),
	/**
	 *  The MCP servers the chosen agent's CLI can see. Claude Code checks each
	 *  server's health, so this can take most of a minute. Empty when no agent
	 *  is chosen.
	 */
	trackerServers: () => typedError<meet_ai_lib_sync_tracker_TrackerServer[], meet_ai_lib_error_UiError>(__TAURI_INVOKE("tracker_servers")),
	/**
	 *  Whether a tracker is set up, and every ticket queued, sending or failed.
	 *  After this, [`crate::events::TICKET_SYNC_EVENT`] keeps it current.
	 */
	ticketSyncStates: () => typedError<meet_ai_lib_sync_auto_TicketSyncOverview, meet_ai_lib_error_UiError>(__TAURI_INVOKE("ticket_sync_states")),
	/**
	 *  Retry: send one root ticket again, even after a failure under the same
	 *  settings. Returns at once; the result comes on
	 *  [`crate::events::TICKET_SYNC_EVENT`].
	 */
	retryTicketSync: (ticketId: string) => typedError<null, meet_ai_lib_error_UiError>(__TAURI_INVOKE("retry_ticket_sync", { ticketId })),
	/**
	 *  Check that the agent reaches `tracker` through `tracker_mcp`, the values
	 *  on screen (saved or not). Creates nothing. Takes as long as the agent
	 *  does (up to `agent.timeout_sec`), so it runs on the blocking pool.
	 */
	sendTestTicket: (tracker: string, trackerMcp: string) => typedError<meet_ai_lib_sync_check_TrackerCheck, meet_ai_lib_error_UiError>(__TAURI_INVOKE("send_test_ticket", { tracker, trackerMcp })),
	/**
	 *  Switch "Make notes for this meeting" on or off (SPEC A11, "Skip one
	 *  meeting", TUR-12), and answer with the meeting's notes as they now stand.
	 * 
	 *  Off writes `agent_notes: off` into `meeting.md` and cancels this
	 *  meeting's notes run if one is going, so nothing more is sent or written.
	 *  On removes the key; the view then offers *Make notes now*, which is
	 *  [`start_notes_run`].
	 */
	setMeetingNotes: (meetingId: string, on: boolean) => typedError<meet_ai_lib_agent_run_MeetingNotes, meet_ai_lib_error_UiError>(__TAURI_INVOKE("set_meeting_notes", { meetingId, on })),
	/**
	 *  Today's events from every configured calendar, local midnight to
	 *  midnight. Denied access is the error kind `calendar-denied`, never an
	 *  empty list.
	 * 
	 *  On the blocking pool: EventKit can wait minutes for the permission answer.
	 */
	todaysMeetings: () => typedError<meet_ai_lib_calendar_TodaysMeetings, meet_ai_lib_error_UiError>(__TAURI_INVOKE("todays_meetings")),
	/**
	 *  `calendar.refresh_minutes` alone: a config read, never the calendar. The
	 *  Today pane asks for it when [`todays_meetings`] fails, so the re-read
	 *  timer follows the config even while access is denied.
	 */
	calendarRefreshMinutes: () => __TAURI_INVOKE<number>("calendar_refresh_minutes"),
	/**
	 *  Sign in to Google or Microsoft in the browser, and return the account.
	 * 
	 *  Errors: `calendar-not-configured` (no client id; the message names the
	 *  `config.jsonc` key), `calendar-sign-in-cancelled` (said no, or no reply in
	 *  5 minutes; a callback without this sign-in's `state` is refused and does
	 *  not end the wait), `calendar-sign-in-failed` (a bad reply, such as a
	 *  provider error; nothing is stored), `calendar-unreachable`.
	 */
	calendarSignIn: (provider: meet_ai_lib_calendar_signin_SignInProvider) => typedError<meet_ai_lib_calendar_signin_CalendarAccount, meet_ai_lib_error_UiError>(__TAURI_INVOKE("calendar_sign_in", { provider })),
	/**  Sign out: forget the access token and delete the stored refresh token. */
	calendarSignOut: (provider: meet_ai_lib_calendar_signin_SignInProvider) => typedError<null, meet_ai_lib_error_UiError>(__TAURI_INVOKE("calendar_sign_out", { provider })),
	/**
	 *  Both providers' sign-in state. The first call after a launch refreshes
	 *  each stored sign-in once, to learn the account and whether it still works.
	 */
	calendarAccounts: () => typedError<meet_ai_lib_calendar_signin_CalendarAccount[], meet_ai_lib_error_UiError>(__TAURI_INVOKE("calendar_accounts")),
	/**
	 *  Which calendar sources this OS offers and which are set up. A config
	 *  read only; never the network or the keystore.
	 */
	calendarSources: () => __TAURI_INVOKE<meet_ai_lib_calendar_sources_CalendarSources>("calendar_sources"),
	/**
	 *  Turn the Calendar app on or off (macOS). On first, so its ids win when a
	 *  meeting is also in a signed-in calendar. Off macOS, turning it on is the
	 *  error kind `calendar-app-unavailable`.
	 */
	setCalendarApp: (on: boolean) => typedError<meet_ai_lib_calendar_sources_CalendarSources, meet_ai_lib_error_UiError>(__TAURI_INVOKE("set_calendar_app", { on })),
	/**
	 *  Sign in to Google or Microsoft in the browser, then read that calendar:
	 *  [`signin::calendar_sign_in`] and the provider added to
	 *  `calendar.providers`. Its errors, plus the config writer's.
	 */
	calendarConnect: (provider: meet_ai_lib_calendar_signin_SignInProvider) => typedError<meet_ai_lib_calendar_signin_CalendarAccount, meet_ai_lib_error_UiError>(__TAURI_INVOKE("calendar_connect", { provider })),
	/**
	 *  Sign out and stop reading that calendar: [`signin::calendar_sign_out`],
	 *  then the provider removed from `calendar.providers`. The sign-out runs
	 *  first, so a config that cannot be written never leaves a token behind.
	 */
	calendarDisconnect: (provider: meet_ai_lib_calendar_signin_SignInProvider) => typedError<meet_ai_lib_calendar_sources_CalendarSources, meet_ai_lib_error_UiError>(__TAURI_INVOKE("calendar_disconnect", { provider })),
	/**
	 *  The brief for the meeting called `title`.
	 * 
	 *  Runs on the blocking pool: it reads the index, a meeting folder and runs
	 *  `git`.
	 */
	meetingBrief: (title: string) => typedError<meet_ai_lib_brief_MeetingBrief, meet_ai_lib_error_UiError>(__TAURI_INVOKE("meeting_brief", { title })),
	/**  `audio.retention_days` as the retention job reads it, for Settings. */
	audioRetentionDays: () => __TAURI_INVOKE<meet_ai_lib_retention_AudioRetentionSetting>("audio_retention_days"),
	/**
	 *  "Stop and quit": let the held quit through. The recording is then
	 *  stopped the same way the Stop button does, off the main thread
	 *  ([`QuitAction::FinishFirst`]).
	 */
	confirmQuit: () => __TAURI_INVOKE<void>("confirm_quit"),
	/**  `app` from `config.jsonc`, defaults when missing or not valid. */
	appSettings: () => typedError<meet_ai_lib_lifecycle_AppSettings, meet_ai_lib_error_UiError>(__TAURI_INVOKE("app_settings")),
	/**
	 *  Save "Show in Dock when the window is closed" and return it as saved.
	 *  Writes under the meetings root, so through the [`FolderGate`].
	 */
	setShowInDockWhenClosed: (show: boolean) => typedError<meet_ai_lib_lifecycle_AppSettings, meet_ai_lib_error_UiError>(__TAURI_INVOKE("set_show_in_dock_when_closed", { show })),
	/**
	 *  Open the logs folder in Finder (Explorer, the file manager on Linux), so
	 *  the user can find the one file to attach to a bug report.
	 */
	openLogsFolder: () => typedError<null, meet_ai_lib_error_UiError>(__TAURI_INVOKE("open_logs_folder")),
	/**
	 *  `app.menu_bar_countdown` (TUR-77): whether the next meeting shows next to
	 *  the menu-bar icon.
	 */
	menuBarCountdown: () => typedError<boolean, meet_ai_lib_error_UiError>(__TAURI_INVOKE("menu_bar_countdown")),
	/**
	 *  Save "Show next meeting in the menu bar" and return it as saved. The menu
	 *  bar picks it up at once rather than at its next minute.
	 */
	setMenuBarCountdown: (show: boolean) => typedError<boolean, meet_ai_lib_error_UiError>(__TAURI_INVOKE("set_menu_bar_countdown", { show })),
	/**  The setting as saved. */
	builtinMicWithBluetooth: () => typedError<boolean, meet_ai_lib_error_UiError>(__TAURI_INVOKE("builtin_mic_with_bluetooth")),
	/**
	 *  Save the setting and return it as saved. Writes under the meetings root,
	 *  so through the [`FolderGate`]. The next mic open uses it.
	 */
	setBuiltinMicWithBluetooth: (on: boolean) => typedError<boolean, meet_ai_lib_error_UiError>(__TAURI_INVOKE("set_builtin_mic_with_bluetooth", { on })),
	/**  `detection` from `config.jsonc`, defaults when missing or not valid. */
	notificationSettings: () => typedError<meet_ai_lib_detection_settings_NotificationSettings, meet_ai_lib_error_UiError>(__TAURI_INVOKE("notification_settings")),
	/**
	 *  Save the card and return what was saved. The loops follow from their
	 *  next tick. Writes under the meetings root, so through the [`FolderGate`].
	 */
	setNotificationSettings: (settings: meet_ai_lib_detection_settings_NotificationSettings) => typedError<meet_ai_lib_detection_settings_NotificationSettings, meet_ai_lib_error_UiError>(__TAURI_INVOKE("set_notification_settings", { settings })),
	/**
	 *  Is the OS blocking meet-ai's notifications? The card then offers the OS
	 *  page that allows them.
	 */
	osNotificationsBlocked: () => __TAURI_INVOKE<boolean>("os_notifications_blocked"),
	/**  Open the OS page where meet-ai's notifications are allowed. */
	openNotificationSettings: () => typedError<null, meet_ai_lib_error_UiError>(__TAURI_INVOKE("open_notification_settings")),
	/**
	 *  "Send a test reminder": a reminder for a fake "Test meeting" starting in
	 *  the configured lead time, through the real prompt path. `false` when
	 *  nothing was shown because a recording is running. Never records.
	 */
	sendTestReminder: () => __TAURI_INVOKE<boolean>("send_test_reminder"),
	/**
	 *  The "Never detect" list (TUR-143): `detection.never_detect`, the apps a
	 *  prompt's "Never for" added or the user wrote in.
	 */
	neverDetectApps: () => typedError<string[], meet_ai_lib_error_UiError>(__TAURI_INVOKE("never_detect_apps")),
	/**
	 *  Save the "Never detect" list (the card's remove buttons) and return what
	 *  was saved. The call-start loop follows from its next reading.
	 */
	setNeverDetectApps: (apps: string[]) => typedError<string[], meet_ai_lib_error_UiError>(__TAURI_INVOKE("set_never_detect_apps", { apps })),
	/**
	 *  **Join**: open the reminded meeting's link in the browser or the app that
	 *  owns it.
	 */
	joinRemindedMeeting: (eventId: string) => typedError<null, meet_ai_lib_error_UiError>(__TAURI_INVOKE("join_reminded_meeting", { eventId })),
	/**
	 *  **Record**, or with `join` **Join and record**: open the link first (a
	 *  link that will not open is logged, and the recording still starts), then
	 *  start a recording named after this meeting.
	 */
	recordRemindedMeeting: (eventId: string, join: boolean) => typedError<meet_ai_lib_recording_Status, meet_ai_lib_error_UiError>(__TAURI_INVOKE("record_reminded_meeting", { eventId, join })),
	/**  The card the popup should show, for a window that just loaded. */
	promptPopupCurrent: () => __TAURI_INVOKE<{
	/**
	 *  This card's id; an answer names it, so a stale click is ignored.
	 *  A JS number: ids count up from 1 and never get near 2^53.
	 */
	id: number,
	card: meet_ai_lib_detection_popup_Card,
	/**
	 *  When the card closes on its own, in Unix milliseconds: the end of a
	 *  prompt's [`AUTO_HIDE`] or of a countdown. The window counts down to
	 *  it and fades out there. A JS number, far below 2^53.
	 */
	closesAtMs: number,
} | null>("prompt_popup_current"),
	/**  A popup button was pressed for card `id`. */
	answerPromptPopup: (id: number, answer: meet_ai_lib_detection_popup_PopupAnswer) => typedError<null, meet_ai_lib_error_UiError>(__TAURI_INVOKE("answer_prompt_popup", { id, answer })),
	/**
	 *  Is the record shortcut meet-ai's (TUR-169)? `false` when registering it
	 *  failed, most likely because another app owns it.
	 */
	recordShortcutAvailable: () => __TAURI_INVOKE<boolean>("record_shortcut_available"),
	/**  Whether meet-ai starts when the user logs in. */
	startAtLogin: () => typedError<boolean, meet_ai_lib_error_UiError>(__TAURI_INVOKE("start_at_login")),
	/**  Turn "Start at login" on or off, and return what the OS now says. */
	setStartAtLogin: (enabled: boolean) => typedError<boolean, meet_ai_lib_error_UiError>(__TAURI_INVOKE("set_start_at_login", { enabled })),
	/**  `appearance` from `config.jsonc`, defaults when missing or not valid. */
	appearanceSettings: () => typedError<meet_ai_lib_config_appearance_section_AppearanceConfig, meet_ai_lib_error_UiError>(__TAURI_INVOKE("appearance_settings")),
	/**
	 *  Save the theme and the glass switch, and return them as saved. Writes
	 *  under the meetings root, so through the [`FolderGate`]. The native
	 *  appearance changes at once.
	 */
	setAppearance: (appearance: meet_ai_lib_config_appearance_section_AppearanceConfig) => typedError<meet_ai_lib_config_appearance_section_AppearanceConfig, meet_ai_lib_error_UiError>(__TAURI_INVOKE("set_appearance", { appearance })),
	/**
	 *  The warning for the recording in progress, `None` when nothing is
	 *  recording or the output has not been read yet.
	 */
	headphoneWarning: () => __TAURI_INVOKE<{
	/**  The meeting being recorded. */
	meetingId: string,
	/**  Show the banner: the output is speakers and the setting is on. */
	show: boolean,
} | null>("headphone_warning"),
	/**
	 *  Why the meetings folder is not being watched, for the Meetings page note
	 *  when it opens; `None` while watching (TUR-134).
	 */
	meetingsWatchProblem: () => __TAURI_INVOKE<string | null>("meetings_watch_problem"),
	/**  `audio.show_recording_overlay`, on unless `config.jsonc` turns it off. */
	showRecordingOverlay: () => typedError<boolean, meet_ai_lib_error_UiError>(__TAURI_INVOKE("show_recording_overlay")),
	/**
	 *  Save the setting and return it as saved. Writes under the meetings root,
	 *  so through the [`FolderGate`]. Takes effect at once: turned off mid-call,
	 *  the overlay closes; turned on, it opens.
	 */
	setShowRecordingOverlay: (on: boolean) => typedError<boolean, meet_ai_lib_error_UiError>(__TAURI_INVOKE("set_show_recording_overlay", { on })),
	/**  The overlay's transcript text was clicked: bring the main window forward. */
	overlayShowMain: () => __TAURI_INVOKE<void>("overlay_show_main"),
	/**
	 *  What in `section` of `config.jsonc` was not valid and is shown as its
	 *  default, or `None` when all of it was valid.
	 */
	configProblem: (section: meet_ai_lib_config_problem_ConfigSection) => typedError<{
	/**  Which error enum this came from: `stt`, `model`, or `app`. */
	domain: string,
	/**  The stable variant tag. Safe to `switch` on. */
	kind: string,
	/**  The error's own sentence. Display it; do not parse it. */
	message: string,
} | null, meet_ai_lib_error_UiError>(__TAURI_INVOKE("config_problem", { section })),
};

/* Constants */
export const AGENT_RUN_STATUS_EVENT = "agent-run://status" as const;

export const DETECTION_PROMPT_EVENT = "detection://prompt" as const;

export const HEADPHONE_WARNING_EVENT = "headphones://warning" as const;

export const HOOK_FAILED_EVENT = "hook://failed" as const;

export const MAX_ATTENDEES = 10 as const;

export const MEETINGS_CHANGED_EVENT = "meetings-changed" as const;

export const MEETINGS_WATCH_PROBLEM_EVENT = "meetings-watch://problem" as const;

export const MIN_ATTENDEES = 1 as const;

export const MODEL_PROGRESS_EVENT = "model://progress" as const;

export const NAVIGATE_EVENT = "app://navigate" as const;

export const PERMISSION_STATUS_EVENT = "permission://status" as const;

export const PROMPT_POPUP_EVENT = "prompt-popup://show" as const;

export const QUIT_CONFIRM_EVENT = "app://confirm-quit" as const;

export const RECORDING_STATE_EVENT = "recording://state" as const;

export const RECORD_SHORTCUT_MAC = "CmdOrCtrl+Shift+R" as const;

export const RECORD_SHORTCUT_OTHER = "Ctrl+Alt+R" as const;

export const TICKET_SYNC_EVENT = "ticket-sync://status" as const;

export const TRANSCRIPT_STATUS_EVENT = "transcript://status" as const;

export const TRANSCRIPT_UPDATE_EVENT = "transcript://update" as const;

/* Types */
/**
 *  The pick the Setup screen shows and saves: `agent.harness`, `agent.model`
 *  and `agent.binary_path`.
 */
export type meet_ai_lib_agent_setup_AgentChoice = {
	harness: meet_ai_lib_agent_setup_AgentHarness,
	/**
	 *  Any model name the CLI accepts. Blank means "Default": no `--model`,
	 *  the CLI picks its own (SPEC A14), and `null` in `config.jsonc`.
	 */
	model: string,
	/**
	 *  Where the CLI is, when the app cannot find it by itself. `null` (or
	 *  blank) means "look for it".
	 */
	binaryPath: string | null,
};

/**  One agent CLI as the Setup screen lists it. */
export type meet_ai_lib_agent_setup_AgentCli = {
	id: meet_ai_lib_agent_setup_AgentCliId,
	/**  "Claude Code" or "Codex". */
	name: string,
	/**
	 *  The company the transcript goes to, for the privacy sentence:
	 *  "Anthropic" or "OpenAI".
	 */
	provider: string,
	state: meet_ai_lib_agent_setup_AgentCliState,
	/**  Where it was found. `null` when it was not. */
	path: string | null,
	/**  What `--version` printed, if anything usable. */
	version: string | null,
	/**  What to type in Terminal to sign in. */
	signInCommand: string,
	/**
	 *  Models for the picker, in order: the first two are the suggestion
	 *  buttons next to "Default", the rest go in the dropdown. The user can
	 *  still type any other name.
	 */
	models: meet_ai_lib_agent_setup_AgentModel[],
	/**
	 *  The model the CLI runs when meet-ai passes none, when its own settings
	 *  say which (Claude Code's `~/.claude/settings.json`, Codex's
	 *  `config.toml`). `null` when they do not; the CLI then uses its
	 *  built-in default.
	 */
	cliDefault: string | null,
	/**  Whether the Test button can run. False only when the CLI is missing. */
	canTest: boolean,
};

/**  One of the agent CLIs the app knows how to run. */
export type meet_ai_lib_agent_setup_AgentCliId = "claude-code" | "codex";

/**  Whether a CLI can run right now. */
export type meet_ai_lib_agent_setup_AgentCliState = 
/**  Found, and signed in. */
"ready" | 
/**  Found, but nobody is signed in. */
"signed-out" | 
/**  Not found on this Mac. */
"missing";

/**  `agent.harness`: which CLI runs the notes, or none (copy prompt instead). */
export type meet_ai_lib_agent_setup_AgentHarness = "claude-code" | "codex" | "none";

/**  One model the picker offers. */
export type meet_ai_lib_agent_setup_AgentModel = {
	/**  What is saved and passed as `--model`: `sonnet`, `gpt-5.6-terra`. */
	name: string,
	/**  What the screen shows: `Sonnet`. The name when there is no label. */
	label: string,
	/**  One line on when to pick it, if meet-ai's list has one. */
	note: string | null,
};

/**  What the test run wrote from the sample meeting. */
export type meet_ai_lib_agent_setup_AgentTestResult = {
	summary: string,
	decisions: string[],
	openQuestions: string[],
	tasks: meet_ai_lib_agent_setup_AgentTestTask[],
	/**
	 *  How long the run took, in whole seconds (rounded). A whole number so
	 *  the wire type is a plain `number`; an `f64` would be `number | null`.
	 */
	seconds: number,
};

/**  One task from the test run. */
export type meet_ai_lib_agent_setup_AgentTestTask = {
	title: string,
	owner: string | null,
	due: string | null,
};

/**  The app settings the Settings screen shows. */
export type meet_ai_lib_lifecycle_AppSettings = {
	/**  macOS: keep the Dock icon while the window is closed. */
	showInDockWhenClosed: boolean,
};

/**  `appearance` in `config.jsonc`, as the Settings screen shows it. */
export type meet_ai_lib_config_appearance_section_AppearanceConfig = {
	theme: meet_ai_lib_config_appearance_section_Theme,
	/**  The see-through sidebar and record prompt. On by default. */
	glass: boolean,
};

/**  What Settings' retention line says. */
export type meet_ai_lib_retention_AudioRetentionSetting = 
/**
 *  The job runs. `days`: `-1` keeps audio forever, `0` deletes it once
 *  the transcript is done, otherwise the days.
 */
{ state: "running"; days: number } | 
/**
 *  No audio is deleted: `config.jsonc` could not be read or parsed, or
 *  its `audio` section is not valid. `reason` says which.
 */
{ state: "paused"; reason: string };

/**  One ticket still open from last time. */
export type meet_ai_lib_brief_BriefTicket = {
	id: string,
	title: string,
	/**  `open` or `in_progress`; `None` when the file has no valid status. */
	status: string | null,
};

/**  One provider's sign-in, for the Settings card. */
export type meet_ai_lib_calendar_signin_CalendarAccount = {
	provider: meet_ai_lib_calendar_signin_SignInProvider,
	/**
	 *  The email address or username. Display only; `null` when not known
	 *  yet (offline right after a restart).
	 */
	account: string | null,
	state: meet_ai_lib_calendar_signin_SignInState,
	/**
	 *  `false`: the OS keystore refused the token (Linux with no Secret
	 *  Service), so this sign-in lasts until the app quits.
	 */
	remembered: boolean,
};

/**  What the Settings card shows before any account is read. */
export type meet_ai_lib_calendar_sources_CalendarSources = {
	/**  This OS has a Calendar app to read (macOS only). */
	calendarAppAvailable: boolean,
	/**  `"eventkit"` is in `calendar.providers`. */
	calendarApp: boolean,
	/**
	 *  The sign-ins with a client id in `config.jsonc`. One without it
	 *  cannot sign in, and the card says which key to add instead.
	 */
	configured: meet_ai_lib_calendar_signin_SignInProvider[],
	/**  The sign-ins named in `calendar.providers`, so read when signed in. */
	connected: meet_ai_lib_calendar_signin_SignInProvider[],
};

/**  What the card asks. */
export type meet_ai_lib_detection_popup_Card = 
/**
 *  "Record this meeting?": a reminder's card for a calendar signal, the
 *  narrow detection card for the rest.
 */
{ kind: "prompt"; prompt: meet_ai_lib_detection_notify_Prompt } | 
/**
 *  "Zoom call ended": stopping in `seconds` unless the user keeps
 *  recording ([`countdown`]).
 */
{ kind: "countdown"; line: string; seconds: number };

/**  One `git log` line. */
export type meet_ai_lib_brief_Commit = {
	/**  The short hash. */
	hash: string,
	subject: string,
};

/**  The `config.jsonc` sections a Settings card shows. */
export type meet_ai_lib_config_problem_ConfigSection = 
/**  Settings, General: the Dock and menu-bar switches. */
"app" | 
/**  Settings, Appearance. */
"appearance" | 
/**  Settings, Notifications. */
"detection";

/**  Whether one choice can be picked, and the sentence to show when not. */
export type meet_ai_lib_engine_choices_EngineAvailability = {
	available: boolean,
	reason: string | null,
};

/**  `transcription.engine`, as the window sends and receives it. */
export type meet_ai_lib_engine_choices_EngineChoice = "auto" | "apple-speech" | "whisper" | "parakeet";

/**  Everything the picker draws. */
export type meet_ai_lib_engine_choices_EngineChoices = {
	/**  What `config.jsonc` says now. */
	engine: meet_ai_lib_engine_choices_EngineChoice,
	/**  `transcription.model`: the whisper model in use when whisper runs. */
	model: string,
	/**  What "Automatic" resolves to on this Mac; `None` when nothing is ready. */
	auto: meet_ai_lib_engine_choices_ResolvedEngine | null,
	apple: meet_ai_lib_engine_choices_EngineAvailability,
	whisper: meet_ai_lib_engine_choices_EngineAvailability,
	/**  Parakeet (TUR-62): pickable once its model folder is downloaded. */
	parakeet: meet_ai_lib_engine_choices_EngineAvailability,
	/**  The Parakeet row's facts and whether its model is here. */
	parakeetModel: meet_ai_lib_engine_parakeet_ParakeetModelView,
	/**  The locales Apple's engine has installed, e.g. `en-US`. */
	languages: string[],
	/**  `transcription.language`: `auto`, or the whisper code people speak. */
	spokenLanguage: string,
	/**
	 *  What the spoken-language picker offers besides `auto`, in its order:
	 *  Hinglish, then every language whisper has a token for, by name.
	 */
	spokenLanguages: meet_ai_lib_engine_choices_SpokenLanguageOption[],
	/**
	 *  What in `transcription` was not valid and is shown as its default
	 *  (TUR-155), such as `"engine": "whispr"`; `None` when all of it was.
	 */
	configProblem: string | null,
};

/**  What the filesystem says, with no subprocess involved. */
export type meet_ai_lib_engine_EnvironmentView = {
	/**
	 *  Absolute path to the `meet-stt` sidecar, if it was found. `None` means
	 *  Apple's engine is not reachable at all on this install.
	 */
	sidecar: string | null,
	/**  Absolute path to a downloaded whisper model, if one is present. */
	whisperModel: string | null,
	locale: string,
	modelId: string,
	/**
	 *  `<meetings root>/.app/models/`, so the screen can name where downloads
	 *  land.
	 */
	modelsDir: string | null,
};

/**  Why a run wrote no notes, in plain words. */
export type meet_ai_lib_agent_run_Failure = {
	kind: meet_ai_lib_agent_run_FailureKind,
	/**  One or two sentences for the meeting view, next to Retry. */
	message: string,
	/**
	 *  A command to type in Terminal that fixes it, when there is one
	 *  (signing in).
	 */
	command: string | null,
};

/**
 *  Every way a run can end without notes. One per thing the user can do
 *  about it.
 */
export type meet_ai_lib_agent_run_FailureKind = 
/**  No agent is set up (`agent.harness` is `none`); Copy prompt instead. */
"no-agent" | 
/**  The chosen agent CLI is not on this Mac, or meet-ai cannot find it. */
"not-installed" | 
/**  The CLI is there but nobody is signed in to it. */
"not-signed-in" | 
/**  The run went past `agent.timeout_sec` and was stopped. */
"timed-out" | 
/**  The user pressed Cancel. */
"cancelled" | 
/**  The CLI exited with an error. */
"cli-failed" | 
/**  The CLI's answer was not JSON, or not in the notes format. */
"bad-reply" | 
/**
 *  The run could not be started (temp folder, launch, prompt template,
 *  config).
 */
"could-not-start" | 
/**  The meeting has no transcript to write notes from. */
"no-transcript" | 
/**  The user switched notes off for this meeting (`agent_notes: off`). */
"notes-off" | 
/**  The answer was fine but writing `meeting.md` or the tickets failed. */
"write-failed";

/**
 *  What [`HEADPHONE_WARNING_EVENT`] carries, and [`headphone_warning`]
 *  returns.
 */
export type meet_ai_lib_headphone_warning_HeadphoneWarning = {
	/**  The meeting being recorded. */
	meetingId: string,
	/**  Show the banner: the output is speakers and the setting is on. */
	show: boolean,
};

/**  One search result. */
export type store_index_Hit = {
	meetingId: string,
	title: string,
	date: string | null,
	/**
	 *  The matching text, each matched word wrapped in [`MATCH_START`] and
	 *  [`MATCH_END`].
	 */
	snippet: string,
	/**  `HH:MM:SS` into the recording; `None` for a title, notes or ticket hit. */
	timestamp: string | null,
};

/**  What [`HOOK_FAILED_EVENT`] carries. */
export type meet_ai_lib_hooks_app_HookFailed = {
	/**  The meeting folder name. */
	meetingId: string,
	/**
	 *  The config key: `on_transcript_ready`, `on_analysis_complete` or
	 *  `on_meeting_end`.
	 */
	hook: string,
	/**  What went wrong, in a few words. */
	message: string,
};

/**
 *  One line on its way to the live pane.
 * 
 *  `start_sec` is fractional here, unlike [`Utterance::start_sec`]. The pane can
 *  show sub-second placement while the `[HH:MM:SS]` line format cannot, and
 *  truncating early would throw the precision away before anyone could use it.
 */
export type stt_session_LiveLine = {
	/**  Meeting-global, monotonic. Stable React key. */
	seq: number,
	speaker: meeting_format_Speaker,
	/**  Seconds from the start of the recording. */
	start_sec: number,
	/**  Already whitespace-collapsed and known non-empty. */
	text: string,
};

/**  Everything the brief view shows for one meeting title. */
export type meet_ai_lib_brief_MeetingBrief = {
	/**  The title asked for, as given. */
	title: string,
	/**
	 *  The last meeting with this title before today; `None` when there is
	 *  none.
	 */
	previous: meet_ai_lib_brief_PreviousMeeting | null,
	/**
	 *  Commits since `previous`; `None` when there is no previous meeting, no
	 *  repo, or the repo cannot be read.
	 */
	commits: meet_ai_lib_brief_RepoCommits | null,
};

/**  A finished meeting, opened for review. */
export type meet_ai_lib_meetings_view_MeetingDetail = {
	summary: meet_ai_lib_meetings_view_MeetingSummary,
	/**  Absolute path, so "Reveal in Finder" and the error copy can name it. */
	path: string,
	lines: meet_ai_lib_meetings_view_TranscriptLine[],
	/**  `transcript.md` is missing entirely — a different state from "empty". */
	transcriptMissing: boolean,
	/**  Lines that did not match §3.4 and were skipped. Surfaced, not hidden. */
	unparsedLineCount: number,
	notes: string,
};

/**  The meeting list plus enough context to write honest empty-state copy. */
export type meet_ai_lib_meetings_list_MeetingList = {
	root: string,
	/**
	 *  The folder does not exist yet. Before the first recording it never does,
	 *  and that is not an error worth alarming anyone about.
	 */
	rootExists: boolean,
	meetings: meet_ai_lib_meetings_view_MeetingSummary[],
};

/**  The agent-written half of `meeting.md`, for the meeting view. */
export type meet_ai_lib_agent_run_MeetingNotes = {
	/**  The meeting is marked `agent_notes: off`. */
	notesOff: boolean,
	/**
	 *  `analyzed_by` (`claude-code`, `codex`, `clipboard`), `None` before any
	 *  notes were written.
	 */
	analyzedBy: string | null,
	/**
	 *  The four sections (Summary, Decisions, Action Items, Open Questions)
	 *  that have text, in that order. Bodies are markdown as written.
	 */
	sections: meet_ai_lib_agent_run_NotesSection[],
};

/**  One row in the meeting list. */
export type meet_ai_lib_meetings_view_MeetingSummary = {
	/**  The folder name, e.g. `2026-09-01-1430-standup`. Also the route param. */
	id: string,
	/**  What to show in the list. */
	title: string,
	/**
	 *  Who was invited, from `meeting.md`'s `attendees` (filled from the
	 *  calendar event, TUR-29). Empty when it names nobody.
	 */
	attendees: string[],
	/**  `YYYY-MM-DD`, parsed from the folder name. `None` if it does not match. */
	date: string | null,
	/**  `HH:MM`, parsed from the folder name. */
	time: string | null,
	/**  How many §3.4 lines parsed. 0 is a real, displayable answer. */
	lineCount: number,
	/**  The timestamp on the last parsed line — the meeting's readable length. */
	lastTimestamp: string | null,
	/**  `notes.md` exists and has something in it. */
	hasNotes: boolean,
	/**
	 *  The meeting has been wrapped up: `meeting.md` exists and its notes are
	 *  written (`analyzed_by` is set, or one of the four sections has text).
	 *  A `meeting.md` that holds only the notes switch does not count.
	 */
	hasAnalysis: boolean,
	/**
	 *  `meeting.md` says `agent_notes: off`: the user switched notes off for
	 *  this meeting (SPEC A11, TUR-12), so no notes run sends it.
	 */
	notesOff: boolean,
	/**  Whether the recording ended on purpose. See [`RecordingState`]. */
	recordingState: meet_ai_lib_recording_state_RecordingState,
	/**
	 *  Milliseconds of audio a player can actually reach: the longer of the
	 *  two tracks, measured from its WAV header (SPEC A5 — header frames are
	 *  the only true duration). `None` when the folder holds no audio at all,
	 *  which is also what a meeting looks like after the retention job (L16)
	 *  has deleted its WAVs.
	 */
	audioMs: number | null,
};

/**  One model licence the app must credit (Settings, About). */
export type meet_ai_lib_engine_parakeet_ModelCredit = {
	/**  The sentence to show, written in `stt`. */
	text: string,
	/**  Where the model and its licence are published. */
	url: string,
};

/**
 *  One word about a model, drawn as a small chip. The UI owns the label for
 *  each, so the wording stays the same on every row.
 */
export type stt_model_ModelTag = "fast" | "light" | "most-accurate" | "multilingual" | "english-only" | "slower";

/**  One row on the model download screen. */
export type meet_ai_lib_engine_ModelView = {
	id: string,
	filename: string,
	/**
	 *  The pinned size. SPEC §2.4's "~1.6 GB" is stale — amendment A4 corrects
	 *  it to 574 MB for turbo and 190 MB for small.en — so the screen reads
	 *  `spec.bytes` rather than quoting either document.
	 */
	bytes: number,
	installed: boolean,
	/**
	 *  The plain-word name, e.g. "Small (English only)" (TUR-79). The id stays
	 *  in the detail line.
	 */
	displayName: string,
	/**  One line on when to pick it. */
	goodFor: string,
	tags: stt_model_ModelTag[],
	/**
	 *  The English names of the languages it understands, in OpenAI's order,
	 *  for the (i) button (TUR-94). `["English"]` for an English-only model.
	 */
	languages: string[],
	/**  Why this is the model to pick on this Mac, set on that one row only. */
	recommended: string | null,
};

/**  A screen Rust sends the window to, on [`NAVIGATE_EVENT`] (TUR-77). */
export type meet_ai_lib_lifecycle_NavigateTo = 
/**  The pre-meeting brief for the meeting called `title` (TUR-32). */
{ to: "brief"; title: string } | 
/**  Settings, where the calendar is connected. */
{ to: "settings" };

export type meet_ai_lib_agent_run_NotesSection = {
	heading: string,
	body: string,
};

/**
 *  What the Notifications card shows and saves: `detection` in
 *  `config.jsonc`.
 */
export type meet_ai_lib_detection_settings_NotificationSettings = {
	/**  "Remind me before meetings": `detection.calendar`. */
	remind: boolean,
	/**
	 *  The lead time: `detection.remind_before_minutes`, 0 to
	 *  [`config::MAX_REMIND_BEFORE_MINUTES`].
	 */
	remindBeforeMinutes: number,
	/**  "Ask when a meeting app is running": `detection.processes`. */
	processes: boolean,
	/**
	 *  "Ask when my mic and speakers are both in use":
	 *  `detection.audio_activity`.
	 */
	audioActivity: boolean,
	/**
	 *  "Only for meetings with at least N people": `detection.min_attendees`,
	 *  [`config::MIN_ATTENDEES`] to [`config::MAX_ATTENDEES`].
	 */
	minAttendees: number,
	/**  "Ask to record when a call starts": `detection.call_start` (TUR-143). */
	callStart: boolean,
	/**  "Ask to stop when a call ends": `detection.call_end` (TUR-144). */
	callEnd: boolean,
	/**
	 *  "Stop after 10 min of silence": `detection.stop_after_silence`
	 *  (TUR-145).
	 */
	stopAfterSilence: boolean,
};

/**
 *  System Settings panes worth deep-linking to.
 * 
 *  SPEC §8.1 left the exact audio-capture anchor to be "verified at
 *  implementation time, falling back to the pane root". Verified on macOS 27.0
 *  (build 26A428) by reading the anchor table out of the Settings extension:
 * 
 *  ```text
 *  strings /System/Library/ExtensionKit/Extensions/SecurityPrivacyExtension.appex/\
 *    Contents/MacOS/SecurityPrivacyExtension | grep -oE 'Privacy_[A-Za-z0-9]+'
 *  ```
 * 
 *  `Privacy_AudioCapture`, `Privacy_Microphone` and `Privacy_Calendars` are
 *  all in that table. The pane root stays as the fallback because an unknown
 *  anchor lands on the root anyway, and because this list will be wrong on
 *  some future macOS.
 */
export type meet_ai_lib_permission_Pane = 
/**  "System Audio Recording Only" — the tap permission. */
"audio-capture" | 
/**  The microphone half, which is a separate grant. */
"microphone" | 
/**
 *  Calendar access, for the Today pane (TUR-28). Never in an audio
 *  [`Status::denied`] list.
 */
"calendars";

/**  The Parakeet row's facts, from the Rust catalogue. */
export type meet_ai_lib_engine_parakeet_ParakeetModelView = {
	/**  The id `download_model` takes. */
	id: string,
	displayName: string,
	goodFor: string,
	/**  Every file together. */
	bytes: number,
	installed: boolean,
	/**
	 *  ONNX Runtime is here to run it. The Windows installer ships
	 *  `onnxruntime.dll` (TUR-104); false only if that file is missing, where
	 *  a download would not help, so none is offered.
	 */
	runtimeReady: boolean,
	/**  English names, in the model card's order, for the (i) button. */
	languages: string[],
};

/**
 *  The paused stretches of the recording, on [`Status::pause`]. The window
 *  works the timer out from these and `started_at_ms`, as it already does,
 *  rather than being sent a tick a second: the elapsed time is the time
 *  since the start, less `paused_total_ms`, frozen at `paused_at_ms` while a
 *  pause runs.
 */
export type meet_ai_lib_recording_pause_PauseClock = {
	/**  Unix epoch milliseconds the current pause began; `None` while recording. */
	pausedAtMs: number | null,
	/**  Milliseconds of every earlier, finished pause, summed. */
	pausedTotalMs: number,
};

/**
 *  Where the recorder is right now.
 * 
 *  `Starting` and `Stopping` are not decoration: opening the tap (the
 *  permission chime now runs after it, TUR-136) and flushing the
 *  last WAV header both take long enough to see, and a shortcut pressed twice
 *  in that window must be ignored rather than queued.
 */
export type meet_ai_lib_recording_phase_Phase = "idle" | "starting" | "recording" | "stopping";

/**  A button in the popup. */
export type meet_ai_lib_detection_popup_PopupAnswer = "record" | "joinAndRecord" | "join" | "openBrief" | 
/**  **Dismiss**, and the detection card's **Not now**. */
"dismiss" | 
/**
 *  The "⋯" menu's **Never for <App>** (TUR-147). The app is the one the
 *  prompt on screen names ([`Prompt::app`]), never one the window sends.
 */
"neverFor" | 
/**  The countdown's **Stop now** (TUR-147). */
"stopNow" | 
/**  The countdown's **Keep recording** (TUR-147). */
"keepRecording";

/**
 *  What the popup window shows, on [`PROMPT_POPUP_EVENT`] and from
 *  [`prompt_popup_current`].
 */
export type meet_ai_lib_detection_popup_PopupPrompt = {
	/**
	 *  This card's id; an answer names it, so a stale click is ignored.
	 *  A JS number: ids count up from 1 and never get near 2^53.
	 */
	id: number,
	card: meet_ai_lib_detection_popup_Card,
	/**
	 *  When the card closes on its own, in Unix milliseconds: the end of a
	 *  prompt's [`AUTO_HIDE`] or of a countdown. The window counts down to
	 *  it and fades out there. A JS number, far below 2^53.
	 */
	closesAtMs: number,
};

/**  What was said last time. */
export type meet_ai_lib_brief_PreviousMeeting = {
	/**  The folder name, e.g. `2026-09-01-1430-standup`. */
	id: string,
	title: string,
	/**  The `date` key as written, `None` when the file has none. */
	date: string | null,
	/**  The `## Summary` text, `None` when blank or missing. */
	summary: string | null,
	/**  The `## Decisions` text, `None` when blank or missing. */
	decisions: string | null,
	/**  Its tickets that are not done or dropped. */
	openTickets: meet_ai_lib_brief_BriefTicket[],
};

/**  What the window hears on [`DETECTION_PROMPT_EVENT`]. */
export type meet_ai_lib_detection_notify_Prompt = {
	/**  What was noticed. */
	signal: detect_Signal,
	/**  Why the user is being asked, as one sentence: "Zoom is open." */
	reason: string,
	/**
	 *  Replace the prompt on screen, if there is one, and open none: this
	 *  call was already asked about (`detection/merge.rs`).
	 */
	updateOnly: boolean,
	/**
	 *  The reminded calendar event (TUR-78), for the banner's Join and
	 *  Record. `None` for other prompts and for a test.
	 */
	eventId: string | null,
	/**  The event has a meeting link: offer **Join and record** and **Join**. */
	canJoin: boolean,
	/**  "Send a test reminder" (TUR-78): the buttons only close the banner. */
	test: boolean,
	/**
	 *  The meeting's name, for the reminder card's first line (TUR-108).
	 *  `None` for a detection prompt, whose card leads with the reason.
	 */
	title: string | null,
	/**
	 *  When the reminded meeting starts and ends, in Unix milliseconds, for
	 *  the card's "9:00 AM to 9:30 AM". `None` when there is no event.
	 *  A JS number: milliseconds since 1970 stay far below 2^53.
	 */
	startsAtMs: number | null,
	endsAtMs: number | null,
	/**
	 *  The service the meeting link joins, for "Join Meet": `"meet"`,
	 *  `"zoom"`, `"teams"` or `"other"` (`join_url::join_service`). `None`
	 *  without a link.
	 */
	joinService: string | null,
	/**
	 *  The card's one line naming what was noticed (TUR-147): "Zoom call",
	 *  "Audio activity", or the meeting's title for a reminder.
	 */
	headline: string,
	/**
	 *  The app the prompt is about, for the card's "Never for Zoom"
	 *  (TUR-147; TUR-143 keeps the list). `None` when no one app explains
	 *  it: audio activity, a reminder.
	 */
	app: string | null,
};

/**
 *  How a meeting's recording ended, as the UI names it (TUR-97).
 * 
 *  **The name for a partly written meeting is "Interrupted".** Chosen over the
 *  alternatives because it says what happened and nothing more:
 * 
 *  * not *failed*, *corrupt* or *error* — the audio and transcript up to the
 *    cut are good, and opening the meeting is not a failure;
 *  * not *incomplete* or *partial* — those suggest the rest might still turn
 *    up, or that the user should go and find it;
 *  * not *recovered* — that implies a repair step the user took part in, and
 *    TUR-97 says there is none;
 *  * and not *finished*, because it is not one: the recording ended because
 *    the app or the Mac stopped, not because someone pressed Stop.
 * 
 *  The list shows the word as a label; the meeting itself says in one line
 *  how much audio was kept.
 */
export type meet_ai_lib_recording_state_RecordingState = 
/**
 *  Stopped on purpose, or there is no audio to judge by (a folder from
 *  before recording existed, or one whose WAVs retention has deleted).
 */
"finished" | 
/**
 *  The recording was cut short — force quit, `kill -9`, a crash, the
 *  battery. Opened exactly like any other meeting.
 */
"interrupted" | 
/**
 *  This app is writing to it right now. Its files look the way an
 *  interrupted meeting's do — the headers are behind the samples and the
 *  last segment has not been closed — because it has not been stopped
 *  *yet*, so it must never be labelled interrupted.
 */
"recording" | 
/**
 *  Stopped cleanly by a backup stop because the computer went to sleep
 *  or its lid closed (TUR-145). Finished in every other way: the files
 *  closed and it plays.
 */
"stopped-for-sleep" | 
/**
 *  Stopped cleanly after ten minutes in which no one spoke and nobody
 *  pressed Keep recording (TUR-145).
 */
"stopped-for-silence";

/**  The repo the meeting is about and what landed in it since last time. */
export type meet_ai_lib_brief_RepoCommits = {
	/**  The repo path as configured, e.g. `~/apps/api`. */
	repo: string,
	/**  What `git log --since` was given. */
	since: string,
	/**  Newest first, at most [`BRIEF_MAX_COMMITS`]. */
	commits: meet_ai_lib_brief_Commit[],
};

/**  An engine that actually runs: what "Automatic" lands on. */
export type meet_ai_lib_engine_choices_ResolvedEngine = "apple-speech" | "whisper" | "parakeet";

/**  Which engine this Mac will actually use, and why. */
export type meet_ai_lib_engine_SelectionView = {
	/**  `apple-speech` or `whisper`. The canonical names from `stt::registry`. */
	engine: string,
	/**  A whole sentence, written by the registry. Shown as-is. */
	reason: string,
};

/**
 *  What the CLI says about a server. Claude Code checks each one; Codex only
 *  reports it as set up.
 */
export type meet_ai_lib_sync_tracker_ServerStatus = "connected" | "needs_auth" | "failed" | "pending" | "disabled" | "configured" | "unknown";

/**  A cloud calendar that needs a sign-in, as the webview names it. */
export type meet_ai_lib_calendar_signin_SignInProvider = "google" | "microsoft";

/**  Whether a provider is signed in. */
export type meet_ai_lib_calendar_signin_SignInState = "signed-in" | 
/**  The provider rejected the stored sign-in: sign in again. */
"expired" | "signed-out";

/**
 *  Why meet-ai thinks a meeting is happening.
 * 
 *  Carried through to the notification copy, so the user is told *why* they are
 *  being asked rather than just being asked.
 */
export type detect_Signal = 
/**  A calendar event with enough attendees starts in a minute. */
{ kind: "calendar"; title: string; attendees: number } | 
/**
 *  A known meeting application is running. `process` is its name as
 *  `processes.json` spells it, e.g. `zoom.us`.
 */
{ kind: "process"; process: string } | 
/**
 *  The mic and the speakers have both been in use for a while
 *  (20 s, see [`activity`]), and no known meeting app explains it — a
 *  call in a browser tab, say.
 */
{ kind: "audio_activity" } | 
/**
 *  A call app or a browser has been using the mic for a while
 *  ([`call_start`], TUR-143). `app` is its name as the user knows it
 *  ("WhatsApp", "Google Chrome"); `browser` says the call is in a tab.
 */
{ kind: "call"; app: string; browser: boolean };

/**
 *  What the `live_transcript` command returns: enough for a window opened
 *  mid-meeting to draw exactly what an always-open one shows.
 */
export type meet_ai_lib_live_transcript_Snapshot = {
	status: meet_ai_lib_live_transcript_Status,
	/**  Every settled line of the current meeting, in arrival order. */
	finals: stt_session_LiveLine[],
	/**  At most one live hypothesis per speaker. */
	volatile: stt_session_LiveLine[],
};

/**
 *  The two speaker labels v1 can produce (L5).
 * 
 *  Serializes lowercase (`"you"`/`"others"`), which is what the live
 *  transcript events carry. That is a wire name, not the file's: the label
 *  written into `transcript.md` is [`Speaker::label`], capitalised, and a
 *  reader that hands parsed lines to the UI serializes that instead (see
 *  `store::transcript::Line`).
 */
export type meeting_format_Speaker = 
/**  The microphone channel — the person using this Mac. */
"you" | 
/**  The system-audio channel — everyone else on the call. */
"others";

/**  One language the spoken-language picker offers. */
export type meet_ai_lib_engine_choices_SpokenLanguageOption = {
	/**  The whisper code, such as `mr`. */
	code: string,
	/**  The English name, such as `Marathi`. */
	name: string,
};

/**
 *  The run's state. `idle` means no run for this meeting since launch: the
 *  view then goes by what is on disk (notes there or not).
 */
export type meet_ai_lib_agent_run_State = { state: "idle" } | 
/**
 *  Stop was pressed and the last transcript lines are still being
 *  written; the run starts on its own once they are (TUR-133).
 */
{ state: "waiting-for-transcript" } | 
/**  *Writing notes…*, with Cancel. */
{ state: "running" } | 
/**
 *  The notes and tasks are on disk. `tasks` is how many tickets were
 *  written.
 */
{ state: "done"; tasks: number } | 
/**  No notes were written, and why. Retry starts again. */
{ state: "failed"; failure: meet_ai_lib_agent_run_Failure };

/**  Where live transcription is. */
export type meet_ai_lib_live_transcript_State = 
/**  Not transcribing: no meeting yet, or the engine is still loading. */
"idle" | 
/**  Lines are being produced. */
"running" | 
/**  The meeting ended and every line that settled is in `transcript.md`. */
"stopped" | 
/**  Transcription ended early. `detail` says why; the recording did not. */
"failed";

/**
 *  Whether onboarding is done, and when.
 * 
 *  One nullable timestamp rather than a boolean plus a date: two fields can
 *  disagree, and "completed but with no date" is a state nobody wants to have
 *  to reason about. The frontend reads `completedAt !== null`.
 */
export type meet_ai_lib_onboarding_State = {
	/**
	 *  When the user finished onboarding, as an RFC 3339 string. `None` means
	 *  they have not.
	 */
	completedAt: string | null,
};

/**  Where the user stands with audio permission. */
export type meet_ai_lib_permission_State = 
/**
 *  Not measured yet. The honest answer until the positive-control tone
 *  check exists.
 */
"unknown" | 
/**  The positive control came back. Recording will capture real audio. */
"granted" | 
/**  The user said No, or the tone did not come back. */
"denied";

/**  Where one meeting's notes run stands, as the meeting view shows it. */
export type meet_ai_lib_agent_run_Status = {
	/**  The meeting folder name. */
	meetingId: string,
	state: meet_ai_lib_agent_run_State,
};

/**  What [`TRANSCRIPT_STATUS_EVENT`] carries. */
export type meet_ai_lib_live_transcript_Status = {
	state: meet_ai_lib_live_transcript_State,
	/**  `apple-speech` or `whisper`, once one has been opened. */
	engine: string | null,
	/**  A sentence for the user when `state` is `failed`. */
	detail: string | null,
};

/**  The permission answer plus enough context for the screen to explain itself. */
export type meet_ai_lib_permission_Status = {
	state: meet_ai_lib_permission_State,
	/**
	 *  Whether a real measurement produced this, or it is the placeholder.
	 * 
	 *  The onboarding screen shows different copy for "we checked and you are
	 *  fine" versus "we cannot check yet", and it must not conflate them.
	 */
	measured: boolean,
	/**
	 *  One sentence naming how the answer was reached. Shown in small print
	 *  under the status row, never in place of the status itself.
	 */
	detail: string,
	/**
	 *  Which grants are off, as the System Settings pane each one lives in, so
	 *  the screen can name the switch to flip rather than "audio" in general.
	 *  Empty unless `state` is `Denied`.
	 */
	denied: meet_ai_lib_permission_Pane[],
};

/**  The recorder's state as the webview sees it. */
export type meet_ai_lib_recording_Status = {
	phase: meet_ai_lib_recording_phase_Phase,
	/**  The folder name of the meeting being recorded, `None` when idle. */
	meetingId: string | null,
	/**
	 *  Unix epoch milliseconds the recording started, so the UI can run its own
	 *  timer instead of being fed a tick per second over IPC.
	 */
	startedAtMs: number | null,
	/**
	 *  Why the last recording ended badly, or the last start was refused: it
	 *  stopped on its own because a tick failed (TUR-97), it did not close
	 *  cleanly, or a start from ⌘⇧R, the menu bar or the button was turned
	 *  down (TUR-127). Only ever set on an `Idle` status, and cleared by the
	 *  next start. It rides on the state event because most of these have no
	 *  command call waiting to return an error to — a recording that ends on
	 *  its own, or a shortcut pressed with the window hidden — and one event
	 *  for the move to `Idle` and its reason means the window can never show
	 *  one without the other. Serialised as `null` when nothing went wrong.
	 */
	error: meet_ai_lib_error_UiError | null,
	/**  The paused stretches, so the timer leaves them out (TUR-146). Boxed: keeps `Status` small. */
	pause: meet_ai_lib_recording_pause_PauseClock,
};

/**  `appearance.theme`: which colour scheme the window uses. */
export type meet_ai_lib_config_appearance_section_Theme = 
/**  Follow the OS, and change with it. */
"system" | "light" | "dark";

/**  One ticket as the webview sees it. */
export type meet_ai_lib_tickets_TicketSummary = {
	id: string,
	title: string,
	/**
	 *  `open`, `in_progress`, `done` or `dropped`; `None` when missing or
	 *  not one of those.
	 */
	status: string | null,
	/**  The meeting folder id it came from; `None` for a hand-made ticket. */
	meeting: string | null,
	body: string,
	/**  The file needs attention (bad YAML, missing id, odd status, ...). */
	hasProblems: boolean,
	/**
	 *  The tracker it was synced to (`linear`, `jira`, `github`); `None`
	 *  until a Sync run created the issue (TUR-11).
	 */
	syncedTo: string | null,
	/**  The issue key the tracker gave it, e.g. `ENG-42`. */
	externalId: string | null,
	/**  The issue's web address. */
	externalUrl: string | null,
	/**
	 *  Still a suggestion in its meeting's own `tickets/` folder, waiting to
	 *  be approved or discarded (SPEC A26). `false` for a ticket in Tickets.
	 */
	suggested: boolean,
	/**  Who it is for (the file's `assignee`). */
	owner: string | null,
	/**  When it is due, as said in the meeting (the body's `Due: X.` line). */
	due: string | null,
	/**  The title of the meeting it came from, for "From: <meeting>". */
	meetingTitle: string | null,
};

/**
 *  What the Tickets page needs to show sending: whether a tracker is set up,
 *  which one, and every ticket queued, sending or failed.
 */
export type meet_ai_lib_sync_auto_TicketSyncOverview = {
	/**  A tracker is chosen in Settings, Tracker and an agent is chosen. */
	trackerSetUp: boolean,
	/**  `linear`, `jira` or `github`, the default when none is set up. */
	tracker: string,
	tickets: meet_ai_lib_sync_auto_TicketSyncStatus[],
};

/**  How far one ticket is in being sent on its own. */
export type meet_ai_lib_sync_auto_TicketSyncState = 
/**
 *  Not sent, and nothing is waiting to send it: no tracker is set up, or
 *  the ticket is gone. The window shows *Not sent* for a ticket with no
 *  issue key.
 */
"not_sent" | 
/**  Waiting for the send before it to finish. */
"queued" | 
/**  The agent is sending it now. */
"sending" | 
/**  In the tracker; `ticket` has its key and link. */
"sent" | 
/**  The send did not create an issue; `error` says why and what to do. */
"failed";

/**  One ticket's state, as [`crate::events::TICKET_SYNC_EVENT`] sends it. */
export type meet_ai_lib_sync_auto_TicketSyncStatus = {
	ticketId: string,
	state: meet_ai_lib_sync_auto_TicketSyncState,
	/**
	 *  Why it was not sent, with a kind the window can switch on
	 *  (`sync::errors`). Only for [`TicketSyncState::Failed`].
	 */
	error: meet_ai_lib_error_UiError | null,
	/**
	 *  The ticket as it is now. Only for [`TicketSyncState::Sent`], and not
	 *  then either when it was found already in the tracker.
	 */
	ticket: meet_ai_lib_tickets_TicketSummary | null,
};

/**  One of today's events, as the Today pane shows it. */
export type meet_ai_lib_calendar_TodayEvent = {
	id: string,
	title: string,
	/**  Start, in milliseconds since the Unix epoch. */
	startMs: number,
	/**  End, in milliseconds since the Unix epoch. */
	endMs: number,
	/**  People invited, rooms not counted. */
	attendees: number,
	/**
	 *  Fewer attendees than `detection.min_attendees`: a focus block or a
	 *  reminder, not a meeting. Shown greyed and never acted on.
	 */
	solo: boolean,
};

/**  What [`todays_meetings`] answers. */
export type meet_ai_lib_calendar_TodaysMeetings = {
	events: meet_ai_lib_calendar_TodayEvent[],
	/**  `calendar.refresh_minutes`: how often the pane asks again. */
	refreshMinutes: number,
	/**  `detection.min_attendees`: below it an event is `solo`. */
	minAttendees: number,
};

/**  What the check found, in plain words. */
export type meet_ai_lib_sync_check_TrackerCheck = {
	/**  The team, project or repository new tickets would go to. */
	project: string,
	/**
	 *  The sentence to show, e.g. "Claude Code reached Linear. New tickets
	 *  will go to Engineering."
	 */
	message: string,
};

/**  One MCP server the agent's CLI lists. */
export type meet_ai_lib_sync_tracker_TrackerServer = {
	name: string,
	status: meet_ai_lib_sync_tracker_ServerStatus,
};

/**  The tracker settings as the window sees them. */
export type meet_ai_lib_sync_tracker_TrackerSettings = {
	/**  `linear`, `jira` or `github`. */
	tracker: string,
	/**  The MCP server name as the agent's CLI lists it. */
	trackerMcp: string,
	/**  `agent.harness`: `claude-code`, `codex` or `none`. */
	harness: string,
	/**
	 *  Whether `config.jsonc` names the tracker and server itself. False when
	 *  `tracker` and `tracker_mcp` are only the shipped defaults: then no
	 *  ticket is sent, and the window must not treat them as saved.
	 */
	chosen: boolean,
};

/**  One parsed transcript line. */
export type meet_ai_lib_meetings_view_TranscriptLine = {
	/**  0-based line number within `transcript.md`, per the Phase 2a contract. */
	seq: number,
	/**  `HH:MM:SS`, the utterance *start* (SPEC §3.4). */
	time: string,
	/**  `You` or `Others` (L5). Kept as the literal spec string. */
	speaker: string,
	text: string,
};

/**  An error as the webview sees it. */
export type meet_ai_lib_error_UiError = {
	/**  Which error enum this came from: `stt`, `model`, or `app`. */
	domain: string,
	/**  The stable variant tag. Safe to `switch` on. */
	kind: string,
	/**  The error's own sentence. Display it; do not parse it. */
	message: string,
};

/**
 *  What [`crate::events::MEETINGS_WATCH_PROBLEM_EVENT`] carries: why the
 *  folder is not being watched, or `None` once it is again.
 */
export type meet_ai_lib_watch_WatchProblem = {
	message: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

