#!/bin/zsh
# Screenshots the review proofs generated by proof.mjs into ../proofs/.
set -e
cd "$(dirname "$0")"
CHROME="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
STAGE="$PWD/.render"
OUT="$PWD/../proofs"
mkdir -p "$OUT"

shoot() {
  local ud; ud=$(mktemp -d)
  rm -f "$2"
  "$CHROME" --headless --disable-gpu --no-first-run --no-default-browser-check \
    --user-data-dir="$ud" --hide-scrollbars --force-device-scale-factor=2 \
    --virtual-time-budget=3000 --screenshot="$2" --window-size="$3,$4" "$1" >/dev/null 2>&1 &
  local pid=$!
  for _ in $(seq 1 80); do [[ -s "$2" ]] && sleep 0.35 && break; sleep 0.25; done
  kill -9 $pid 2>/dev/null || true; wait $pid 2>/dev/null || true; rm -rf "$ud"
  [[ -s "$2" ]] || { echo "failed: $2" >&2; exit 1 }
  echo "   $2:t"
}

echo "-- proofs"
shoot "file://$STAGE/proof-icon.html"    "$OUT/proof-app-icon.png"   1180 1760
shoot "file://$STAGE/proof-menubar.html" "$OUT/proof-menu-bar.png"    900  760
shoot "file://$STAGE/proof-logo.html"    "$OUT/proof-logo-system.png" 760 1180
shoot "file://$STAGE/proof-readme.html"  "$OUT/proof-in-context.png" 1010  680
shoot "file://$STAGE/proof-misuse.html"  "$OUT/proof-misuse.png"     1000  780
shoot "file://$PWD/../concepts/_directions.html" "$OUT/proof-directions.png" 1080 1080
