//! The Phase 0 drift-gate fixture suite, asserted against `segments.rs`.
//!
//! Fixtures live in `crates/audio/fixtures/segments/` and are generated by
//! `just fixtures` (`fixtures/generate-segments.py`). Each `segments.json` is
//! committed: the on-disk shape is half of what is under test here, so these
//! assertions deliberately go through `Segments::from_json` rather than
//! building `Segment` values in Rust.
//!
//! Every expected value below comes from the fixture spec on TUR-7
//! (`#document-fixture-spec`), which in turn derives from SPEC amendment A5
//! (`SPEC.md:520`). The rule that produced the suite: **a gate that has never
//! been observed to fail is not known to work** — so every threshold gets a
//! pair, one fixture just under and one just over.
//!
//! `refuse-one-anchor` was the one contested row: the spec's §3 rationale
//! predated A5 and no longer applies. Resolved on TUR-4 — see the test below.

use std::path::PathBuf;

use audio::Channel;
use audio::segments::{
    CHECKPOINT_INTERVAL_S, CLOSE_ANCHOR_SLACK_MS, DriftError, DriftReport, FINAL_TAIL_SLACK_MS,
    Segments, SegmentsDrift, reason,
};

/// The fixture spec's tolerance on every expected value: ±1 frame at 16 kHz.
/// Frame counts are integers, so a ppm-derived expectation lands at most half a
/// frame off the value a fixture can actually express.
const FRAME_MS: f64 = 1000.0 / 16_000.0;

const GATE_MS: f64 = 200.0;
const FORTY_FIVE_MINUTES_S: u64 = 45 * 60;

fn fixture_dir(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("fixtures/segments")
        .join(name)
}

fn load(name: &str) -> Segments {
    let path = fixture_dir(name).join("segments.json");
    let json = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "{}: {e} — run `just fixtures` to generate it",
            path.display()
        )
    });
    Segments::from_json(&json)
        .unwrap_or_else(|e| panic!("{} is not a valid segments.json: {e}", path.display()))
}

#[track_caller]
fn assert_ms(actual: f64, expected: f64, what: &str) {
    assert!(
        (actual - expected).abs() <= FRAME_MS,
        "{what}: measured {actual} ms, spec says {expected} ms (tolerance ±1 frame = {FRAME_MS} ms)"
    );
}

// ---------------------------------------------------------------------------
// §2 — drift fixtures
//
// One 2700 s segment, 540 anchors, synthesised against
//   drift = frames/16000 − (host_ns − start_host_ns)/1e9
// so a clock `p` ppm fast reads `elapsed_s × p / 1e6`. Over 2700 s the 200 ms
// gate sits at exactly 74.07 ppm, which is what the 74/75 pair straddles.
// ---------------------------------------------------------------------------

/// Assert the four `DriftReport` numbers the spec's §2 table states, plus the
/// anchor count, for a single-segment 45-minute fixture.
#[track_caller]
fn assert_drift_row(
    name: &str,
    mic_ms: f64,
    sys_ms: f64,
    skew_ms: f64,
    passes: bool,
) -> DriftReport {
    let report = load(name)
        .drift()
        .unwrap_or_else(|e| panic!("{name} must measure, not refuse: {e}"));

    assert_ms(
        report.mic.max_abs_ms,
        mic_ms,
        &format!("{name} mic max_abs_ms"),
    );
    assert_ms(report.mic.final_ms, mic_ms, &format!("{name} mic final_ms"));
    assert_ms(
        report.system.max_abs_ms,
        sys_ms,
        &format!("{name} system max_abs_ms"),
    );
    assert_ms(
        report.system.final_ms,
        sys_ms,
        &format!("{name} system final_ms"),
    );
    assert_ms(
        report.max_track_skew_ms,
        skew_ms,
        &format!("{name} max_track_skew_ms"),
    );

    assert_eq!(
        report.passes(GATE_MS),
        passes,
        "{name}: passes({GATE_MS}) was {} — worst channel measured {} ms",
        report.passes(GATE_MS),
        report.worst_ms()
    );

    // 2700 s of 5 s checkpoints, and nothing recorded past the last one.
    let expected_anchors = (FORTY_FIVE_MINUTES_S / CHECKPOINT_INTERVAL_S) as usize;
    assert_eq!(report.mic.anchors, expected_anchors, "{name} mic anchors");
    assert_eq!(
        report.system.anchors, expected_anchors,
        "{name} system anchors"
    );
    assert_ms(
        report.mic.tail_unanchored_ms,
        0.0,
        &format!("{name} mic tail"),
    );

    // One segment means no boundaries to cost.
    assert!(
        report.boundary_gaps.is_empty(),
        "{name}: {:?}",
        report.boundary_gaps
    );
    report
}

#[test]
fn drift_clean_0ppm_measures_zero() {
    let report = assert_drift_row("drift-clean-0ppm", 0.0, 0.0, 0.0, true);
    assert!(
        report.mic.first_breach.is_none(),
        "a true clock breached the gate: {:?}",
        report.mic.first_breach
    );
}

#[test]
fn drift_pass_50ppm_measures_135ms_on_the_mic_alone() {
    let report = assert_drift_row("drift-pass-50ppm", 135.0, 0.0, 135.0, true);
    assert!(
        report.mic.first_breach.is_none(),
        "{:?}",
        report.mic.first_breach
    );
}

/// The lower half of the boundary pair. 199.8 ms — must pass.
#[test]
fn drift_edge_74ppm_is_under_the_gate_and_passes() {
    let report = assert_drift_row("drift-edge-74ppm", 199.8, 0.0, 199.8, true);
    assert!(
        report.mic.first_breach.is_none(),
        "199.8 ms is under a 200 ms gate, but first_breach was {:?}",
        report.mic.first_breach
    );
}

/// The upper half. 202.5 ms — must fail. Together with the 74 ppm row this
/// pins the threshold where §12 claims it is, in both directions, to 2.7 ms.
#[test]
fn drift_edge_75ppm_is_over_the_gate_and_fails() {
    let report = assert_drift_row("drift-edge-75ppm", 202.5, 0.0, 202.5, false);

    // 0.375 ms per checkpoint, so the curve crosses 200 ms at the anchor
    // covering 2670 s, where it reads 200.25 ms.
    let breach = report
        .mic
        .first_breach
        .expect("the gate was crossed at 2670 s");
    assert!(
        (breach.elapsed_s - 2670.0).abs() <= CHECKPOINT_INTERVAL_S as f64,
        "crossed at {} s, expected 2670 s ±1 checkpoint",
        breach.elapsed_s
    );
    assert_ms(breach.drift_ms, 200.25, "drift-edge-75ppm breach drift_ms");
}

#[test]
fn drift_fail_100ppm_measures_270ms_and_reports_when_it_crossed() {
    let report = assert_drift_row("drift-fail-100ppm", 270.0, 0.0, 270.0, false);

    // 0.5 ms per checkpoint reaches 200 ms at 2000 s. The comparison at that
    // anchor is `drift.abs() >= 200.0` on a value that is 200 ms only to within
    // a double's last bit, so the crossing is allowed to land on the next
    // checkpoint — hence ±1 checkpoint rather than an equality.
    let breach = report
        .mic
        .first_breach
        .expect("the gate was crossed at ~2000 s");
    assert!(
        (breach.elapsed_s - 2000.0).abs() <= CHECKPOINT_INTERVAL_S as f64,
        "crossed at {} s, expected 2000 s ±1 checkpoint",
        breach.elapsed_s
    );
}

/// The regression test for the original blocker.
///
/// Both device clocks run 100 ppm fast — one pair of AirPods feeding mic and
/// output. The pre-A5 quantity `(mic_frames − sys_frames) / 16000` reads 0 ms
/// on this recording and would have certified it. If this fixture ever passes
/// the gate, the tool has regressed to the broken metric.
#[test]
fn drift_common_mode_100ppm_is_invisible_to_a_track_subtraction_and_caught_anyway() {
    let recording = load("drift-common-mode-100ppm");

    let naive_ms = (recording.total_frames(Channel::Mic) as f64
        - recording.total_frames(Channel::System) as f64)
        * 1000.0
        / 16_000.0;
    assert_ms(naive_ms, 0.0, "the pre-A5 track-vs-track metric");

    let report = assert_drift_row("drift-common-mode-100ppm", 270.0, 270.0, 0.0, false);
    assert!(
        report.mic.first_breach.is_some() && report.system.first_breach.is_some(),
        "both channels crossed the gate but only one reported it: {report:?}"
    );
}

// ---------------------------------------------------------------------------
// §3 — refusal fixtures
//
// `drift()` must refuse rather than flatter. An `Ok` here is a gate-certifying
// bug, not a cosmetic one: it is a passing number printed for a recording whose
// timeline nobody measured.
// ---------------------------------------------------------------------------

/// A failed process tap. Treating the missing track as `sys_frames = 0` and
/// subtracting reports a flattering number for a recording with no system audio
/// in it at all, so the supported signal is `sys_rate: 0` and no `system.wav`.
#[test]
fn refuse_no_system_refuses_instead_of_subtracting_against_zero() {
    let fixture = load("refuse-no-system");
    assert_eq!(fixture.segments[0].sys_rate, 0);
    assert_eq!(fixture.segments[0].mic_rate, 16_000);
    assert!(
        !fixture_dir("refuse-no-system").join("system.wav").exists(),
        "absent, not zero-length, is the supported signal"
    );

    assert_eq!(
        fixture.drift().unwrap_err(),
        DriftError::ChannelAbsent(Channel::System)
    );
}

/// The contradictory shape: frames were written, but the rate field says the
/// track never started. Proves the absent check keys on rate, not on frames —
/// if it keyed on frames this file would measure and report a clean 0 ms.
#[test]
fn refuse_zero_rate_refuses_even_though_frames_are_present() {
    let fixture = load("refuse-zero-rate");
    assert_eq!(fixture.segments[0].sys_rate, 0);
    assert!(
        fixture.segments[0].sys_frames > 0,
        "the fixture must carry the contradiction"
    );

    assert_eq!(
        fixture.drift().unwrap_err(),
        DriftError::ChannelAbsent(Channel::System)
    );
}

/// A revision-1-shaped file. Frame counts alone compare the two tracks against
/// each other and never against a clock — that is the whole reason A5 exists.
#[test]
fn refuse_no_anchors_refuses_a_pre_a5_file() {
    let fixture = load("refuse-no-anchors");
    assert!(fixture.segments[0].anchors.is_empty());

    assert_eq!(fixture.drift().unwrap_err(), DriftError::NoAnchors);
}

#[test]
fn refuse_nonmonotonic_rejects_a_host_clock_that_goes_backwards() {
    let err = load("refuse-nonmonotonic").drift().unwrap_err();

    assert!(
        matches!(
            err,
            DriftError::NonMonotonic {
                field: "mic_host_ns",
                segment: 0,
                anchor: 59
            }
        ),
        "expected a NonMonotonic refusal naming mic_host_ns, got {err:?}"
    );
}

/// **F2.** The row I cared most about, and the one the anchors were added for.
///
/// The segment declares 2700 s of frames; the anchors stop at 300 s. Without a
/// coverage refusal this measures 3 ms over the five minutes it can see, says
/// nothing about the forty it cannot, and returns a passing number — the exact
/// failure mode A5 exists to eliminate, one level down. `tail_unanchored_ms`
/// surfaced the uncovered tail, but surfacing is not refusing.
///
/// A single segment is also the *last* segment, so it gets the generous
/// `kill -9` slack (one checkpoint plus drain) rather than the 250 ms a
/// deliberate close gets — and 2400 s clears that by three orders of magnitude.
#[test]
fn refuse_anchors_stop_early_refuses_a_recording_it_only_partly_measured() {
    let err = load("refuse-anchors-stop-early").drift().unwrap_err();

    let DriftError::AnchorCoverage {
        segment,
        channel,
        uncovered_ms,
        slack_ms,
        closed_deliberately,
    } = err
    else {
        panic!("2400 s of this recording carry no anchor, but drift() said {err:?}");
    };
    assert_eq!((segment, channel), (0, Channel::Mic));
    assert!(!closed_deliberately, "a single segment is the last segment");
    assert_ms(uncovered_ms, 2_400_024.0, "unmeasured audio");
    assert_ms(
        slack_ms,
        FINAL_TAIL_SLACK_MS,
        "slack for a killed recording",
    );
}

/// A stubbed clock: 60 checkpoints, every one reporting the host time of the
/// first, while the frames keep arriving.
///
/// `NonMonotonic` alone does not catch this — it tests `now < before`, and a
/// frozen clock never goes backwards. The gate would have failed this file
/// anyway, because the drift number explodes, but exit 1 and exit 2 mean
/// different things: "your hardware drifted" sends someone hunting a clock bug
/// that is not there, while "not measurable" points at the recorder.
#[test]
fn refuse_frozen_clock_refuses_a_stubbed_host_clock() {
    let err = load("refuse-frozen-clock").drift().unwrap_err();

    assert!(
        matches!(
            err,
            DriftError::FrozenClock {
                segment: 0,
                anchor: 1,
                field: "mic_host_ns"
            }
        ),
        "expected a FrozenClock refusal at the first repeated anchor, got {err:?}"
    );
}

/// Beyond the spec's seven rows, and the dangerous sibling of the one above.
///
/// Here the anchor latch itself is stuck, so host time *and* frames repeat.
/// Every drift then reads exactly 0 and the drift number cannot save us: the
/// gate passes and a recording nobody measured certifies itself. Only a
/// refusal that keys on the repeated host clock catches it, which is why the
/// monotonicity test has to reject `now == before` on the host fields rather
/// than only `now < before`.
#[test]
fn refuse_frozen_clock_and_frames_refuses_a_stuck_anchor_latch() {
    let err = load("refuse-frozen-clock-and-frames").drift().unwrap_err();

    assert!(
        matches!(
            err,
            DriftError::FrozenClock {
                field: "mic_host_ns",
                ..
            }
        ),
        "60 identical anchors would have certified the recording, got {err:?}"
    );
}

/// **Resolved on TUR-4, by Rune: measures, does not refuse.**
///
/// The fixture spec's §3 rationale — "nothing to difference" — predates A5 and
/// no longer holds: A5 measures each anchor against `start_host_ns`, not
/// anchor-to-anchor, so one anchor covering its whole segment is one valid
/// host-clock-referenced point. `max_abs_ms` and `final_ms` are both
/// well-defined from a single sample; what a single anchor cannot show is a
/// *slope*, and a minimum-anchor-count rule for that belongs to the future
/// slope feature (F3: `drift-check` prints `n/a` below 2 measured anchors),
/// which has nothing in `DriftReport` to attach to yet and is not this
/// function's refusal to make.
///
/// The dimension `Segments::drift()` already gates on is *coverage*: a single
/// anchor that leaves most of its segment's audio unmeasured still refuses via
/// `AnchorCoverage`, same as zero anchors would. This fixture's one anchor
/// covers its whole 5 s segment, so there is nothing uncovered.
#[test]
fn a_single_anchor_that_covers_its_whole_segment_is_a_valid_point_measurement() {
    let report = load("single-anchor-measures")
        .drift()
        .expect("one anchor covering its whole segment is a measurement, not a refusal");

    assert_eq!(report.mic.anchors, 1);
    assert_ms(report.mic.max_abs_ms, 0.0, "single-anchor mic drift");
    assert_ms(report.mic.final_ms, 0.0, "single-anchor mic final drift");
    assert_ms(
        report.mic.tail_unanchored_ms,
        0.0,
        "fully covered by its one anchor",
    );
    assert!(report.passes(GATE_MS), "{report:?}");
}

// ---------------------------------------------------------------------------
// §4 — device-switch fixtures
//
// A segment boundary is unrecorded wall clock and SPEC A5 refuses to pad it, so
// "survives a device switch" has to come out as a number rather than a yes/no
// somebody asserted by listening.
// ---------------------------------------------------------------------------

/// Seg 0 closes on the checkpoint grid, so its last anchor is the close anchor.
/// The AirPods swap costs 400 ms of wall clock and must read as 400 ms — and
/// must not be charged to either device clock as drift.
#[test]
fn device_switch_400ms_costs_exactly_400ms_of_unrecorded_wall_clock() {
    let report = load("device-switch-400ms").drift().unwrap();

    assert_eq!(report.boundary_gaps.len(), 1);
    let gap = &report.boundary_gaps[0];
    assert_eq!(gap.reason, reason::DEFAULT_OUTPUT_DEVICE_CHANGED);
    assert_ms(gap.mic_ms, 400.0, "device-switch-400ms mic gap");
    assert_ms(gap.sys_ms, 400.0, "device-switch-400ms system gap");
    // A device switch is not a sleep: host and continuous time agree on it.
    assert_ms(
        gap.asleep_ms.expect("both segments carry continuous time"),
        0.0,
        "asleep",
    );

    assert_ms(report.mic.max_abs_ms, 0.0, "the gap must not land in drift");
    assert!(report.passes(GATE_MS), "{report:?}");
    assert_eq!(report.mic.anchors, 480, "240 checkpoints either side");
}

/// A **negative** fixture: seg 0 closes 4.2 s after its last ordinary
/// checkpoint, so there is no close anchor. It encodes the F1 bug on purpose,
/// so that removing the close-anchor call site fails a test instead of quietly
/// degrading a number.
///
/// Two things worth pinning about what it actually does.
///
/// The spec predicted the *gap* would inflate to ~4600 ms here. It does not:
/// `boundary_gap` differences the segment frame totals, which are current at
/// close, so the close anchor was never on the gap path. F1 as written does not
/// reproduce.
///
/// What it does instead is refuse outright — and that is the stronger answer.
/// Seg 0 is not the last segment, so it was closed deliberately and gets 250 ms
/// of slack for the final ring-buffer drain, not the 5 s a `kill -9` gets. 4.2 s
/// of audio no anchor ever measured is a corrupt file, not a ragged shutdown.
#[test]
fn device_switch_without_a_close_anchor_refuses_the_whole_recording() {
    let err = load("device-switch-no-close-anchor").drift().unwrap_err();

    let DriftError::AnchorCoverage {
        segment,
        channel,
        uncovered_ms,
        slack_ms,
        closed_deliberately,
    } = err
    else {
        panic!("a deliberate close left 4.2 s unmeasured, but drift() said {err:?}");
    };
    assert_eq!((segment, channel), (0, Channel::Mic));
    assert!(closed_deliberately, "seg 0 is followed by seg 1");
    assert_ms(uncovered_ms, 4200.0, "seg 0's unanchored tail");
    assert_ms(
        slack_ms,
        CLOSE_ANCHOR_SLACK_MS,
        "slack for a deliberate close",
    );

    // The gap itself is still computable and still correct — the refusal is
    // about coverage, not about the boundary arithmetic.
    let gap = &load("device-switch-no-close-anchor").boundary_gaps()[0];
    assert_ms(gap.mic_ms, 400.0, "gap with no close anchor");
    assert_ms(gap.sys_ms, 400.0, "gap with no close anchor");
}

/// Two anchors in the entire recording — one per segment — and seg 1 stops 3 s
/// past its only checkpoint.
///
/// The spec's row asserts `slope: n/a` below 3 anchors (F3). `DriftReport`
/// exposes no slope at all, so there is nothing here to mark `n/a`; the
/// requirement applies to whatever `drift-check` eventually prints. What this
/// fixture can pin today is that a thin recording still yields an honest anchor
/// count and keeps its ragged tail out of the drift number.
#[test]
fn device_switch_short_tail_keeps_teardown_out_of_the_drift_number() {
    let report = load("device-switch-short-tail").drift().unwrap();

    assert_eq!(report.mic.anchors, 2, "two anchors total, one per segment");
    assert_ms(report.mic.tail_unanchored_ms, 3000.0, "seg 1's 3 s tail");
    assert_ms(report.mic.max_abs_ms, 0.0, "tail audio is not drift");
    assert_ms(
        report.boundary_gaps[0].mic_ms,
        400.0,
        "the switch still cost 400 ms",
    );
    assert!(report.passes(GATE_MS), "{report:?}");
}

/// Both segments run at +100 ppm for 1200 s. Each re-anchors to the host clock
/// at its own `start_host_ns`, so the gate number is the **max over segments**
/// (120 ms, passes) and never the sum (240 ms, fails).
///
/// This pins semantics that look wrong at a glance, so that nobody later
/// "fixes" drift into accumulating across a boundary.
#[test]
fn device_switch_drift_reset_reports_the_max_over_segments_not_the_sum() {
    let report = load("device-switch-drift-reset").drift().unwrap();

    assert_ms(report.mic.max_abs_ms, 120.0, "per-segment max");
    assert_ms(report.mic.final_ms, 120.0, "seg 1's last anchor");
    assert_ms(report.system.max_abs_ms, 120.0, "per-segment max");
    assert!(
        report.mic.max_abs_ms < 240.0,
        "drift accumulated across the boundary: {} ms",
        report.mic.max_abs_ms
    );
    assert!(
        report.passes(GATE_MS),
        "1200 s at 100 ppm is 120 ms, under the gate: {report:?}"
    );
}
